//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMS() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CMS", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 允许增加内容 的本地化字符串。
        /// </summary>
        internal static string CCAddContent {
            get {
                return ResourceManager.GetString("CCAddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 允许增加子类 的本地化字符串。
        /// </summary>
        internal static string CCAddSubclass {
            get {
                return ResourceManager.GetString("CCAddSubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 文章列表 的本地化字符串。
        /// </summary>
        internal static string CCArticleList {
            get {
                return ResourceManager.GetString("CCArticleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您所选的父级栏目不允许添加子栏目，请先修改父级栏目！ 的本地化字符串。
        /// </summary>
        internal static string CCErrorAddClass {
            get {
                return ResourceManager.GetString("CCErrorAddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目编号格式不正确 的本地化字符串。
        /// </summary>
        internal static string CCErrorClassID {
            get {
                return ResourceManager.GetString("CCErrorClassID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部展开 的本地化字符串。
        /// </summary>
        internal static string CCExpandAll {
            get {
                return ResourceManager.GetString("CCExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目描述 的本地化字符串。
        /// </summary>
        internal static string CCFieldDescription {
            get {
                return ResourceManager.GetString("CCFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目图片 的本地化字符串。
        /// </summary>
        internal static string CCFieldImageUrl {
            get {
                return ResourceManager.GetString("CCFieldImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上级菜单 的本地化字符串。
        /// </summary>
        internal static string CCFieldParentId {
            get {
                return ResourceManager.GetString("CCFieldParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目编号 的本地化字符串。
        /// </summary>
        internal static string CClassID {
            get {
                return ResourceManager.GetString("CClassID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分类名称 的本地化字符串。
        /// </summary>
        internal static string CClassification {
            get {
                return ResourceManager.GetString("CClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目类型 的本地化字符串。
        /// </summary>
        internal static string CClassType {
            get {
                return ResourceManager.GetString("CClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增栏目 的本地化字符串。
        /// </summary>
        internal static string CClblAdd {
            get {
                return ResourceManager.GetString("CClblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以添加、编辑、删除栏目内容 的本地化字符串。
        /// </summary>
        internal static string CClblAlist {
            get {
                return ResourceManager.GetString("CClblAlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以进行栏目编辑 的本地化字符串。
        /// </summary>
        internal static string CClblModify {
            get {
                return ResourceManager.GetString("CClblModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目详细信息查看 的本地化字符串。
        /// </summary>
        internal static string CClblShow {
            get {
                return ResourceManager.GetString("CClblShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部收缩 的本地化字符串。
        /// </summary>
        internal static string CCollapseAll {
            get {
                return ResourceManager.GetString("CCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目索引 的本地化字符串。
        /// </summary>
        internal static string CColumnIndex {
            get {
                return ResourceManager.GetString("CColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容模式 的本地化字符串。
        /// </summary>
        internal static string CContentModel {
            get {
                return ResourceManager.GetString("CContentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 顺序值 的本地化字符串。
        /// </summary>
        internal static string CCOrder {
            get {
                return ResourceManager.GetString("CCOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加栏目 的本地化字符串。
        /// </summary>
        internal static string CCptAdd {
            get {
                return ResourceManager.GetString("CCptAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目管理 的本地化字符串。
        /// </summary>
        internal static string CCptAlist {
            get {
                return ResourceManager.GetString("CCptAlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑栏目 的本地化字符串。
        /// </summary>
        internal static string CCptModify {
            get {
                return ResourceManager.GetString("CCptModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目详细 的本地化字符串。
        /// </summary>
        internal static string CCptShow {
            get {
                return ResourceManager.GetString("CCptShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询方式 的本地化字符串。
        /// </summary>
        internal static string CCSearchMethod {
            get {
                return ResourceManager.GetString("CCSearchMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 显示模式 的本地化字符串。
        /// </summary>
        internal static string CCShowType {
            get {
                return ResourceManager.GetString("CCShowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 单文章 的本地化字符串。
        /// </summary>
        internal static string CCSingleArticle {
            get {
                return ResourceManager.GetString("CCSingleArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 页面模板名称 的本地化字符串。
        /// </summary>
        internal static string CCTemplateName {
            get {
                return ResourceManager.GetString("CCTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 父级类别 的本地化字符串。
        /// </summary>
        internal static string CCTheParent {
            get {
                return ResourceManager.GetString("CCTheParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 无父级 的本地化字符串。
        /// </summary>
        internal static string CCTooltipNoParent {
            get {
                return ResourceManager.GetString("CCTooltipNoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加失败，请稍后再试！ 的本地化字符串。
        /// </summary>
        internal static string ClassErrorAddFailed {
            get {
                return ResourceManager.GetString("ClassErrorAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目类型名称不能为空! 的本地化字符串。
        /// </summary>
        internal static string ClassErrorCLassNameNull {
            get {
                return ResourceManager.GetString("ClassErrorCLassNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目类型格式不正确！ 的本地化字符串。
        /// </summary>
        internal static string ClassErrorFormatError {
            get {
                return ResourceManager.GetString("ClassErrorFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ClassErrorNameNotNull {
            get {
                return ResourceManager.GetString("ClassErrorNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类型编号 的本地化字符串。
        /// </summary>
        internal static string ClasslblClassID {
            get {
                return ResourceManager.GetString("ClasslblClassID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类型名称 的本地化字符串。
        /// </summary>
        internal static string ClasslblClassName {
            get {
                return ResourceManager.GetString("ClasslblClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增栏目类型 的本地化字符串。
        /// </summary>
        internal static string ClasslblCmsClass {
            get {
                return ResourceManager.GetString("ClasslblCmsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑栏目类型 的本地化字符串。
        /// </summary>
        internal static string ClasslblList {
            get {
                return ResourceManager.GetString("ClasslblList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑栏目类型 的本地化字符串。
        /// </summary>
        internal static string ClasslblModify {
            get {
                return ResourceManager.GetString("ClasslblModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增栏目类型 的本地化字符串。
        /// </summary>
        internal static string ClassptCmsClass {
            get {
                return ResourceManager.GetString("ClassptCmsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类型管理 的本地化字符串。
        /// </summary>
        internal static string ClassptList {
            get {
                return ResourceManager.GetString("ClassptList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑栏目类型 的本地化字符串。
        /// </summary>
        internal static string ClassptModify {
            get {
                return ResourceManager.GetString("ClassptModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入类型名称！ 的本地化字符串。
        /// </summary>
        internal static string ClasstooltipEnterName {
            get {
                return ResourceManager.GetString("ClasstooltipEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 文章类别名称 的本地化字符串。
        /// </summary>
        internal static string ContentClassName {
            get {
                return ResourceManager.GetString("ContentClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设为已审核 的本地化字符串。
        /// </summary>
        internal static string ContentdropAudit {
            get {
                return ResourceManager.GetString("ContentdropAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设为未审核 的本地化字符串。
        /// </summary>
        internal static string ContentdropDraftList {
            get {
                return ResourceManager.GetString("ContentdropDraftList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设为草稿 的本地化字符串。
        /// </summary>
        internal static string ContentdropNotApprove {
            get {
                return ResourceManager.GetString("ContentdropNotApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 草稿 的本地化字符串。
        /// </summary>
        internal static string ContentdrpDraft {
            get {
                return ResourceManager.GetString("ContentdrpDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 -选择批量处理类型- 的本地化字符串。
        /// </summary>
        internal static string ContentdrpSelect {
            get {
                return ResourceManager.GetString("ContentdrpSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请先添加栏目！ 的本地化字符串。
        /// </summary>
        internal static string ContentErrorAddClass {
            get {
                return ResourceManager.GetString("ContentErrorAddClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 所属栏目类别不允许添加内容，请先修改所属栏目类别允许添加子类！ 的本地化字符串。
        /// </summary>
        internal static string ContentErrorAddContent {
            get {
                return ResourceManager.GetString("ContentErrorAddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 所属栏目为单文章模式，不允许添加多个内容！ 的本地化字符串。
        /// </summary>
        internal static string ContentErrorAddMoreContent {
            get {
                return ResourceManager.GetString("ContentErrorAddMoreContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容编号格式不正确！ 的本地化字符串。
        /// </summary>
        internal static string ContentErrorContentID {
            get {
                return ResourceManager.GetString("ContentErrorContentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入正整数 的本地化字符串。
        /// </summary>
        internal static string ContentErrorInputInt {
            get {
                return ResourceManager.GetString("ContentErrorInputInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信息已被删除或者不存在！ 的本地化字符串。
        /// </summary>
        internal static string ContentErrorNoContent {
            get {
                return ResourceManager.GetString("ContentErrorNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 *标题不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ContentErrorTitleNotNull {
            get {
                return ResourceManager.GetString("ContentErrorTitleNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 详细 的本地化字符串。
        /// </summary>
        internal static string ContentfieldContentID {
            get {
                return ResourceManager.GetString("ContentfieldContentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建日期 的本地化字符串。
        /// </summary>
        internal static string ContentfieldCreatedDate {
            get {
                return ResourceManager.GetString("ContentfieldCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 浏览数 的本地化字符串。
        /// </summary>
        internal static string ContentfieldPvCount {
            get {
                return ResourceManager.GetString("ContentfieldPvCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关键字列表 的本地化字符串。
        /// </summary>
        internal static string ContentKeywordList {
            get {
                return ResourceManager.GetString("ContentKeywordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增内容 的本地化字符串。
        /// </summary>
        internal static string ContentlblAdd {
            get {
                return ResourceManager.GetString("ContentlblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 附件 的本地化字符串。
        /// </summary>
        internal static string ContentlblAppendix {
            get {
                return ResourceManager.GetString("ContentlblAppendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择栏目 的本地化字符串。
        /// </summary>
        internal static string ContentlblClass {
            get {
                return ResourceManager.GetString("ContentlblClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 栏目名称 的本地化字符串。
        /// </summary>
        internal static string ContentlblClassName {
            get {
                return ResourceManager.GetString("ContentlblClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 所属栏目类别 的本地化字符串。
        /// </summary>
        internal static string ContentlblClassType {
            get {
                return ResourceManager.GetString("ContentlblClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容编号 的本地化字符串。
        /// </summary>
        internal static string ContentlblContentID {
            get {
                return ResourceManager.GetString("ContentlblContentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容属性 的本地化字符串。
        /// </summary>
        internal static string ContentlblContentProperty {
            get {
                return ResourceManager.GetString("ContentlblContentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建者编号 的本地化字符串。
        /// </summary>
        internal static string ContentlblCreatedID {
            get {
                return ResourceManager.GetString("ContentlblCreatedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建用户 的本地化字符串。
        /// </summary>
        internal static string ContentlblCreater {
            get {
                return ResourceManager.GetString("ContentlblCreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 下载 的本地化字符串。
        /// </summary>
        internal static string ContentlblDownload {
            get {
                return ResourceManager.GetString("ContentlblDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 醒目 的本地化字符串。
        /// </summary>
        internal static string ContentlblEyeCatching {
            get {
                return ResourceManager.GetString("ContentlblEyeCatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 文件地址 的本地化字符串。
        /// </summary>
        internal static string ContentlblFileUrl {
            get {
                return ResourceManager.GetString("ContentlblFileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 热点 的本地化字符串。
        /// </summary>
        internal static string ContentlblHotSpot {
            get {
                return ResourceManager.GetString("ContentlblHotSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最后修改日期 的本地化字符串。
        /// </summary>
        internal static string ContentlblLastDate {
            get {
                return ResourceManager.GetString("ContentlblLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最后修改人 的本地化字符串。
        /// </summary>
        internal static string ContentlblLaster {
            get {
                return ResourceManager.GetString("ContentlblLaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 外部链接地址 的本地化字符串。
        /// </summary>
        internal static string ContentlblLinkUrl {
            get {
                return ResourceManager.GetString("ContentlblLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增、编辑内容 的本地化字符串。
        /// </summary>
        internal static string ContentlblList {
            get {
                return ResourceManager.GetString("ContentlblList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 仅会员可见 的本地化字符串。
        /// </summary>
        internal static string ContentlblMemberOnly {
            get {
                return ResourceManager.GetString("ContentlblMemberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑内容 的本地化字符串。
        /// </summary>
        internal static string ContentlblModify {
            get {
                return ResourceManager.GetString("ContentlblModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容权限 的本地化字符串。
        /// </summary>
        internal static string ContentlblPermissions {
            get {
                return ResourceManager.GetString("ContentlblPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 推荐 的本地化字符串。
        /// </summary>
        internal static string ContentlblRecommend {
            get {
                return ResourceManager.GetString("ContentlblRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以浏览内容信息 的本地化字符串。
        /// </summary>
        internal static string ContentlblShow {
            get {
                return ResourceManager.GetString("ContentlblShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 置顶 的本地化字符串。
        /// </summary>
        internal static string ContentlblTop {
            get {
                return ResourceManager.GetString("ContentlblTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 浏览量 的本地化字符串。
        /// </summary>
        internal static string ContentlblViews {
            get {
                return ResourceManager.GetString("ContentlblViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加内容 的本地化字符串。
        /// </summary>
        internal static string ContentptAdd {
            get {
                return ResourceManager.GetString("ContentptAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容管理 的本地化字符串。
        /// </summary>
        internal static string ContentptList {
            get {
                return ResourceManager.GetString("ContentptList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑内容 的本地化字符串。
        /// </summary>
        internal static string ContentptModify {
            get {
                return ResourceManager.GetString("ContentptModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容信息 的本地化字符串。
        /// </summary>
        internal static string ContentptShow {
            get {
                return ResourceManager.GetString("ContentptShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发布 的本地化字符串。
        /// </summary>
        internal static string ContentRelease {
            get {
                return ResourceManager.GetString("ContentRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 否 的本地化字符串。
        /// </summary>
        internal static string ContentReleaseNo {
            get {
                return ResourceManager.GetString("ContentReleaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是 的本地化字符串。
        /// </summary>
        internal static string ContentReleaseYes {
            get {
                return ResourceManager.GetString("ContentReleaseYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 文章标题 的本地化字符串。
        /// </summary>
        internal static string ContentTitle {
            get {
                return ResourceManager.GetString("ContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你确定要批量处理？ 的本地化字符串。
        /// </summary>
        internal static string ContentTooltipBatch {
            get {
                return ResourceManager.GetString("ContentTooltipBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 附件删除成功！ 的本地化字符串。
        /// </summary>
        internal static string ContentTooltipDelete {
            get {
                return ResourceManager.GetString("ContentTooltipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 附件删除失败，请稍后再试！ 的本地化字符串。
        /// </summary>
        internal static string ContentTooltipDeleteFail {
            get {
                return ResourceManager.GetString("ContentTooltipDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已经存在同名标题的文章！ 的本地化字符串。
        /// </summary>
        internal static string ContentTooltipTitleExist {
            get {
                return ResourceManager.GetString("ContentTooltipTitleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传附件成功！ 的本地化字符串。
        /// </summary>
        internal static string ContentTooltipUpload {
            get {
                return ResourceManager.GetString("ContentTooltipUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 例如：http://www.ys56.com 的本地化字符串。
        /// </summary>
        internal static string ContenttoortipUrl {
            get {
                return ResourceManager.GetString("ContenttoortipUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 固定页面内容 的本地化字符串。
        /// </summary>
        internal static string FixedPageContent {
            get {
                return ResourceManager.GetString("FixedPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑固定页面内容 的本地化字符串。
        /// </summary>
        internal static string FixedPageContentEdit {
            get {
                return ResourceManager.GetString("FixedPageContentEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 页面名称 的本地化字符串。
        /// </summary>
        internal static string FixedPageName {
            get {
                return ResourceManager.GetString("FixedPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增，编辑文章（新闻）内容 的本地化字符串。
        /// </summary>
        internal static string lblContentManage {
            get {
                return ResourceManager.GetString("lblContentManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 文章(新闻)管理 的本地化字符串。
        /// </summary>
        internal static string ptContentManage {
            get {
                return ResourceManager.GetString("ptContentManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入标题名称！ 的本地化字符串。
        /// </summary>
        internal static string TitleErrorAddContent {
            get {
                return ResourceManager.GetString("TitleErrorAddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 可用 的本地化字符串。
        /// </summary>
        internal static string WMAvailable {
            get {
                return ResourceManager.GetString("WMAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户自定义 的本地化字符串。
        /// </summary>
        internal static string WMCustom {
            get {
                return ResourceManager.GetString("WMCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单名称 的本地化字符串。
        /// </summary>
        internal static string WMenuName {
            get {
                return ResourceManager.GetString("WMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string WMErrorMenuName {
            get {
                return ResourceManager.GetString("WMErrorMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 页面地址不能为空！ 的本地化字符串。
        /// </summary>
        internal static string WMErrorPageUrl {
            get {
                return ResourceManager.GetString("WMErrorPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 显示序号不能为空！ 的本地化字符串。
        /// </summary>
        internal static string WMErrorSqueeze {
            get {
                return ResourceManager.GetString("WMErrorSqueeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 显示序号格式不正确！ 的本地化字符串。
        /// </summary>
        internal static string WMErrorSqueezeForm {
            get {
                return ResourceManager.GetString("WMErrorSqueezeForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否可用 的本地化字符串。
        /// </summary>
        internal static string WMIsAvailable {
            get {
                return ResourceManager.GetString("WMIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增导航菜单 的本地化字符串。
        /// </summary>
        internal static string WMlblAdd {
            get {
                return ResourceManager.GetString("WMlblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新窗口 的本地化字符串。
        /// </summary>
        internal static string WMlblBlank {
            get {
                return ResourceManager.GetString("WMlblBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以添加、编辑自定义网站前台顶部导航菜单 的本地化字符串。
        /// </summary>
        internal static string WMlblList {
            get {
                return ResourceManager.GetString("WMlblList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你可以自定义网站参数 的本地化字符串。
        /// </summary>
        internal static string WMlblModify {
            get {
                return ResourceManager.GetString("WMlblModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 本窗口 的本地化字符串。
        /// </summary>
        internal static string WMlblSelf {
            get {
                return ResourceManager.GetString("WMlblSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 打开方式 的本地化字符串。
        /// </summary>
        internal static string WMlblTarget {
            get {
                return ResourceManager.GetString("WMlblTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 不可用 的本地化字符串。
        /// </summary>
        internal static string WMNotAvailable {
            get {
                return ResourceManager.GetString("WMNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新建导航菜单 的本地化字符串。
        /// </summary>
        internal static string WMptAdd {
            get {
                return ResourceManager.GetString("WMptAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导航菜单管理 的本地化字符串。
        /// </summary>
        internal static string WMptList {
            get {
                return ResourceManager.GetString("WMptList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑导航菜单 的本地化字符串。
        /// </summary>
        internal static string WMptModify {
            get {
                return ResourceManager.GetString("WMptModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统 的本地化字符串。
        /// </summary>
        internal static string WMSystem {
            get {
                return ResourceManager.GetString("WMSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统菜单 的本地化字符串。
        /// </summary>
        internal static string WMSystemMenu {
            get {
                return ResourceManager.GetString("WMSystemMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 标题名称 的本地化字符串。
        /// </summary>
        internal static string WMTitleName {
            get {
                return ResourceManager.GetString("WMTitleName", resourceCulture);
            }
        }
    }
}
