//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMSPhoto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMSPhoto() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CMSPhoto", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 相册名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorAlbumNull {
            get {
                return ResourceManager.GetString("ErrorAlbumNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类别名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorClassNameNull {
            get {
                return ResourceManager.GetString("ErrorClassNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类别名称已经存在，请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string ErrorClassRepeat {
            get {
                return ResourceManager.GetString("ErrorClassRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorImageNameNull {
            get {
                return ResourceManager.GetString("ErrorImageNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 简介不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorIntroductionNull {
            get {
                return ResourceManager.GetString("ErrorIntroductionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 标签不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 顺序格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorOrderFormat {
            get {
                return ResourceManager.GetString("ErrorOrderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string lblabel {
            get {
                return ResourceManager.GetString("lblabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以添加相册 的本地化字符串。
        /// </summary>
        internal static string lblAddAlbum {
            get {
                return ResourceManager.GetString("lblAddAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以上传相片 的本地化字符串。
        /// </summary>
        internal static string lblAddPhoto {
            get {
                return ResourceManager.GetString("lblAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑图片信息 的本地化字符串。
        /// </summary>
        internal static string lblAddPhotoInfo {
            get {
                return ResourceManager.GetString("lblAddPhotoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以添加图片分类 的本地化字符串。
        /// </summary>
        internal static string lblAddPrictureClass {
            get {
                return ResourceManager.GetString("lblAddPrictureClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 相册 的本地化字符串。
        /// </summary>
        internal static string lblAlbum {
            get {
                return ResourceManager.GetString("lblAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 相册ID 的本地化字符串。
        /// </summary>
        internal static string lblAlbumID {
            get {
                return ResourceManager.GetString("lblAlbumID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对相册进行管理，包括添加，删除等。 的本地化字符串。
        /// </summary>
        internal static string lblAlbumList {
            get {
                return ResourceManager.GetString("lblAlbumList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑相册信息 的本地化字符串。
        /// </summary>
        internal static string lblAlbumModify {
            get {
                return ResourceManager.GetString("lblAlbumModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 相册名称 的本地化字符串。
        /// </summary>
        internal static string lblAlbumName {
            get {
                return ResourceManager.GetString("lblAlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string lblAlbumType {
            get {
                return ResourceManager.GetString("lblAlbumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 原图文件名（大） 的本地化字符串。
        /// </summary>
        internal static string lblArtworkName {
            get {
                return ResourceManager.GetString("lblArtworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择相册 的本地化字符串。
        /// </summary>
        internal static string lblChooseAlbum {
            get {
                return ResourceManager.GetString("lblChooseAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分类 的本地化字符串。
        /// </summary>
        internal static string lblClassification {
            get {
                return ResourceManager.GetString("lblClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对图片类别进行管理 的本地化字符串。
        /// </summary>
        internal static string lblClassList {
            get {
                return ResourceManager.GetString("lblClassList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑图片分类 的本地化字符串。
        /// </summary>
        internal static string lblClassModify {
            get {
                return ResourceManager.GetString("lblClassModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 评论数 的本地化字符串。
        /// </summary>
        internal static string lblComments {
            get {
                return ResourceManager.GetString("lblComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 相册封面 的本地化字符串。
        /// </summary>
        internal static string lblCoverPictures {
            get {
                return ResourceManager.GetString("lblCoverPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建日期 的本地化字符串。
        /// </summary>
        internal static string lblCreateData {
            get {
                return ResourceManager.GetString("lblCreateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建时间 的本地化字符串。
        /// </summary>
        internal static string lblCreateDate {
            get {
                return ResourceManager.GetString("lblCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建用户 的本地化字符串。
        /// </summary>
        internal static string lblCreater {
            get {
                return ResourceManager.GetString("lblCreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建用户ID 的本地化字符串。
        /// </summary>
        internal static string lblCreaterID {
            get {
                return ResourceManager.GetString("lblCreaterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 当前封面 的本地化字符串。
        /// </summary>
        internal static string lblFrontCover {
            get {
                return ResourceManager.GetString("lblFrontCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否推荐 的本地化字符串。
        /// </summary>
        internal static string lblIsRecommend {
            get {
                return ResourceManager.GetString("lblIsRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最后更新日期 的本地化字符串。
        /// </summary>
        internal static string lblLastDate {
            get {
                return ResourceManager.GetString("lblLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对图片进行管理 的本地化字符串。
        /// </summary>
        internal static string lblList {
            get {
                return ResourceManager.GetString("lblList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 正常图（中） 的本地化字符串。
        /// </summary>
        internal static string lblNormal {
            get {
                return ResourceManager.GetString("lblNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 浏览量 的本地化字符串。
        /// </summary>
        internal static string lblPageViews {
            get {
                return ResourceManager.GetString("lblPageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上级类别 的本地化字符串。
        /// </summary>
        internal static string lblParentsClass {
            get {
                return ResourceManager.GetString("lblParentsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片分类 的本地化字符串。
        /// </summary>
        internal static string lblPictureClass {
            get {
                return ResourceManager.GetString("lblPictureClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 隐私 的本地化字符串。
        /// </summary>
        internal static string lblPrivacy {
            get {
                return ResourceManager.GetString("lblPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 推荐 的本地化字符串。
        /// </summary>
        internal static string lblRecommend {
            get {
                return ResourceManager.GetString("lblRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设为封面 的本地化字符串。
        /// </summary>
        internal static string lblSetToCover {
            get {
                return ResourceManager.GetString("lblSetToCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 缩略图（小） 的本地化字符串。
        /// </summary>
        internal static string lblThumbnails {
            get {
                return ResourceManager.GetString("lblThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string lblUrl {
            get {
                return ResourceManager.GetString("lblUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查看原图 的本地化字符串。
        /// </summary>
        internal static string lblViewOriginal {
            get {
                return ResourceManager.GetString("lblViewOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 可见性 的本地化字符串。
        /// </summary>
        internal static string lblVisibility {
            get {
                return ResourceManager.GetString("lblVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片名称 的本地化字符串。
        /// </summary>
        internal static string PrictureName {
            get {
                return ResourceManager.GetString("PrictureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加相册 的本地化字符串。
        /// </summary>
        internal static string ptAddAlbum {
            get {
                return ResourceManager.GetString("ptAddAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传相片 的本地化字符串。
        /// </summary>
        internal static string ptAddPhoto {
            get {
                return ResourceManager.GetString("ptAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑图片信息 的本地化字符串。
        /// </summary>
        internal static string ptAddPhotoInfo {
            get {
                return ResourceManager.GetString("ptAddPhotoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加图片分类 的本地化字符串。
        /// </summary>
        internal static string ptAddPrictureClass {
            get {
                return ResourceManager.GetString("ptAddPrictureClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 相册管理 的本地化字符串。
        /// </summary>
        internal static string ptAlbumList {
            get {
                return ResourceManager.GetString("ptAlbumList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑相册 的本地化字符串。
        /// </summary>
        internal static string ptAlbumModify {
            get {
                return ResourceManager.GetString("ptAlbumModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 相册信息 的本地化字符串。
        /// </summary>
        internal static string ptAlbumShow {
            get {
                return ResourceManager.GetString("ptAlbumShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片类别管理 的本地化字符串。
        /// </summary>
        internal static string ptClassList {
            get {
                return ResourceManager.GetString("ptClassList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑图片分类 的本地化字符串。
        /// </summary>
        internal static string ptClassModify {
            get {
                return ResourceManager.GetString("ptClassModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片分类信息 的本地化字符串。
        /// </summary>
        internal static string ptClassShow {
            get {
                return ResourceManager.GetString("ptClassShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片管理 的本地化字符串。
        /// </summary>
        internal static string ptList {
            get {
                return ResourceManager.GetString("ptList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片信息 的本地化字符串。
        /// </summary>
        internal static string ptPrictureShow {
            get {
                return ResourceManager.GetString("ptPrictureShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传图片失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string TooltipAddFail {
            get {
                return ResourceManager.GetString("TooltipAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传图片成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipAddSucceed {
            get {
                return ResourceManager.GetString("TooltipAddSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipEditedSuccess {
            get {
                return ResourceManager.GetString("TooltipEditedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 多个标签，请用“，”分割！ 的本地化字符串。
        /// </summary>
        internal static string TooltipLabel {
            get {
                return ResourceManager.GetString("TooltipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置封面 的本地化字符串。
        /// </summary>
        internal static string TooltipSetCpver {
            get {
                return ResourceManager.GetString("TooltipSetCpver", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置封面失败！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSetToCoverFail {
            get {
                return ResourceManager.GetString("TooltipSetToCoverFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置封面成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSetToCoverSuccess {
            get {
                return ResourceManager.GetString("TooltipSetToCoverSuccess", resourceCulture);
            }
        }
    }
}
