//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMSVideo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMSVideo() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CMSVideo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 专辑 的本地化字符串。
        /// </summary>
        internal static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 专辑与分类 的本地化字符串。
        /// </summary>
        internal static string AlbumAndCategory {
            get {
                return ResourceManager.GetString("AlbumAndCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分类名称 的本地化字符串。
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部收缩 的本地化字符串。
        /// </summary>
        internal static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分类名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorClassNameNull {
            get {
                return ResourceManager.GetString("ErrorClassNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未上传视频！ 的本地化字符串。
        /// </summary>
        internal static string ErrorNoVideo {
            get {
                return ResourceManager.GetString("ErrorNoVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 顺序格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorOrderFormat {
            get {
                return ResourceManager.GetString("ErrorOrderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 隐私格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorPrivacyFormed {
            get {
                return ResourceManager.GetString("ErrorPrivacyFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 状态格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorStartFormat {
            get {
                return ResourceManager.GetString("ErrorStartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 标题不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorTitleNull {
            get {
                return ResourceManager.GetString("ErrorTitleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorVideoNameNull {
            get {
                return ResourceManager.GetString("ErrorVideoNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 视频标题不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorVideoTitleNull {
            get {
                return ResourceManager.GetString("ErrorVideoTitleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 视频类型格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorVideoType {
            get {
                return ResourceManager.GetString("ErrorVideoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部展开 的本地化字符串。
        /// </summary>
        internal static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传失败！ 的本地化字符串。
        /// </summary>
        internal static string hfUploadFails {
            get {
                return ResourceManager.GetString("hfUploadFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传成功！ 的本地化字符串。
        /// </summary>
        internal static string hfUploadSuccess {
            get {
                return ResourceManager.GetString("hfUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名称不能为空,长度限制在100个字符以内！ 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_AlbumName_Description {
            get {
                return ResourceManager.GetString("IDS_Message_AlbumName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 标题不能为空,长度限制在200个字符以内！ 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_Title_Description {
            get {
                return ResourceManager.GetString("IDS_Message_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名称不能为空,长度限制在100个字符以内！ 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_VideoClassName_Description {
            get {
                return ResourceManager.GetString("IDS_Message_VideoClassName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否推荐 的本地化字符串。
        /// </summary>
        internal static string IsRecommend {
            get {
                return ResourceManager.GetString("IsRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网络视频预览 的本地化字符串。
        /// </summary>
        internal static string LineVideoPreview {
            get {
                return ResourceManager.GetString("LineVideoPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 本地视频 的本地化字符串。
        /// </summary>
        internal static string LocalVideo {
            get {
                return ResourceManager.GetString("LocalVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 本地视频预览 的本地化字符串。
        /// </summary>
        internal static string LocalVideoPreview {
            get {
                return ResourceManager.GetString("LocalVideoPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 专辑 的本地化字符串。
        /// </summary>
        internal static string ltlAlbum {
            get {
                return ResourceManager.GetString("ltlAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 附件 的本地化字符串。
        /// </summary>
        internal static string ltlAttachment {
            get {
                return ResourceManager.GetString("ltlAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 取消上传 的本地化字符串。
        /// </summary>
        internal static string ltlCancelUpload {
            get {
                return ResourceManager.GetString("ltlCancelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分类 的本地化字符串。
        /// </summary>
        internal static string ltlCategory {
            get {
                return ResourceManager.GetString("ltlCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 封面 的本地化字符串。
        /// </summary>
        internal static string ltlCoverVideo {
            get {
                return ResourceManager.GetString("ltlCoverVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建时间 的本地化字符串。
        /// </summary>
        internal static string ltlCreatedDate {
            get {
                return ResourceManager.GetString("ltlCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建者 的本地化字符串。
        /// </summary>
        internal static string ltlCreatedUser {
            get {
                return ResourceManager.GetString("ltlCreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 层级 的本地化字符串。
        /// </summary>
        internal static string ltlDepth {
            get {
                return ResourceManager.GetString("ltlDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 域名 的本地化字符串。
        /// </summary>
        internal static string ltlDomain {
            get {
                return ResourceManager.GetString("ltlDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 下载 的本地化字符串。
        /// </summary>
        internal static string ltlDownload {
            get {
                return ResourceManager.GetString("ltlDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 时长 的本地化字符串。
        /// </summary>
        internal static string ltlDuration {
            get {
                return ResourceManager.GetString("ltlDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 格式 的本地化字符串。
        /// </summary>
        internal static string ltlFormat {
            get {
                return ResourceManager.GetString("ltlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 评分 的本地化字符串。
        /// </summary>
        internal static string ltlGrade {
            get {
                return ResourceManager.GetString("ltlGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 时 的本地化字符串。
        /// </summary>
        internal static string ltlHours {
            get {
                return ResourceManager.GetString("ltlHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 截图 的本地化字符串。
        /// </summary>
        internal static string ltlImageUrl {
            get {
                return ResourceManager.GetString("ltlImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最后编辑时间 的本地化字符串。
        /// </summary>
        internal static string ltlLastUpdateDate {
            get {
                return ResourceManager.GetString("ltlLastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最后编辑者 的本地化字符串。
        /// </summary>
        internal static string ltlLastUpdateUser {
            get {
                return ResourceManager.GetString("ltlLastUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分 的本地化字符串。
        /// </summary>
        internal static string ltlMinutes {
            get {
                return ResourceManager.GetString("ltlMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备选缩略图 的本地化字符串。
        /// </summary>
        internal static string ltlNormalImageUrl {
            get {
                return ResourceManager.GetString("ltlNormalImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string ltlPath {
            get {
                return ResourceManager.GetString("ltlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 隐私 的本地化字符串。
        /// </summary>
        internal static string ltlPrivacy {
            get {
                return ResourceManager.GetString("ltlPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 浏览量 的本地化字符串。
        /// </summary>
        internal static string ltlPvCount {
            get {
                return ResourceManager.GetString("ltlPvCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分享数 的本地化字符串。
        /// </summary>
        internal static string ltlReference {
            get {
                return ResourceManager.GetString("ltlReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string ltlRemark {
            get {
                return ResourceManager.GetString("ltlRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string ltlSeconds {
            get {
                return ResourceManager.GetString("ltlSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 顺序 的本地化字符串。
        /// </summary>
        internal static string ltlSequence {
            get {
                return ResourceManager.GetString("ltlSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网址 的本地化字符串。
        /// </summary>
        internal static string ltlSite {
            get {
                return ResourceManager.GetString("ltlSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 粘贴视频播放页地址(支持优酷、酷六) 的本地化字符串。
        /// </summary>
        internal static string ltlSiteTip {
            get {
                return ResourceManager.GetString("ltlSiteTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string ltlTags {
            get {
                return ResourceManager.GetString("ltlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 *多个标签之间用逗号&apos;,&apos;分隔。 的本地化字符串。
        /// </summary>
        internal static string ltlTagsTip {
            get {
                return ResourceManager.GetString("ltlTagsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 缩略图 的本地化字符串。
        /// </summary>
        internal static string ltlThumbImageUrl {
            get {
                return ResourceManager.GetString("ltlThumbImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string ltlTitle {
            get {
                return ResourceManager.GetString("ltlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 评论数 的本地化字符串。
        /// </summary>
        internal static string ltlTotalComment {
            get {
                return ResourceManager.GetString("ltlTotalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 收藏数 的本地化字符串。
        /// </summary>
        internal static string ltlTotalFav {
            get {
                return ResourceManager.GetString("ltlTotalFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 顶数 的本地化字符串。
        /// </summary>
        internal static string ltlTotalUp {
            get {
                return ResourceManager.GetString("ltlTotalUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string ltlType {
            get {
                return ResourceManager.GetString("ltlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传 的本地化字符串。
        /// </summary>
        internal static string ltlUpload {
            get {
                return ResourceManager.GetString("ltlUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传视频 的本地化字符串。
        /// </summary>
        internal static string ltlUploadVideo {
            get {
                return ResourceManager.GetString("ltlUploadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 暂无分类 的本地化字符串。
        /// </summary>
        internal static string NoCategory {
            get {
                return ResourceManager.GetString("NoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未审核 的本地化字符串。
        /// </summary>
        internal static string NotAudit {
            get {
                return ResourceManager.GetString("NotAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已审核未发布 的本地化字符串。
        /// </summary>
        internal static string NotYetReleased {
            get {
                return ResourceManager.GetString("NotYetReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网络视频 的本地化字符串。
        /// </summary>
        internal static string OnlineVideo {
            get {
                return ResourceManager.GetString("OnlineVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 对所有人公开 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查看原视频 的本地化字符串。
        /// </summary>
        internal static string OriginalVideo {
            get {
                return ResourceManager.GetString("OriginalVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 收起 的本地化字符串。
        /// </summary>
        internal static string PackUp {
            get {
                return ResourceManager.GetString("PackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 父类 的本地化字符串。
        /// </summary>
        internal static string ParentClass {
            get {
                return ResourceManager.GetString("ParentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 待审核 的本地化字符串。
        /// </summary>
        internal static string PendingReview {
            get {
                return ResourceManager.GetString("PendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 仅自己可见 的本地化字符串。
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增视频信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoAdd {
            get {
                return ResourceManager.GetString("ptVideoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoAddTip {
            get {
                return ResourceManager.GetString("ptVideoAddTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增视频专辑 的本地化字符串。
        /// </summary>
        internal static string ptVideoAlbumAdd {
            get {
                return ResourceManager.GetString("ptVideoAlbumAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增专辑信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoAlbumAddTip {
            get {
                return ResourceManager.GetString("ptVideoAlbumAddTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 视频专辑管理 的本地化字符串。
        /// </summary>
        internal static string ptVideoAlbumList {
            get {
                return ResourceManager.GetString("ptVideoAlbumList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增、删除、编辑、查看视频专辑 的本地化字符串。
        /// </summary>
        internal static string ptVideoAlbumListTip {
            get {
                return ResourceManager.GetString("ptVideoAlbumListTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑视频专辑 的本地化字符串。
        /// </summary>
        internal static string ptVideoAlbumModify {
            get {
                return ResourceManager.GetString("ptVideoAlbumModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑专辑信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoAlbumModifyTip {
            get {
                return ResourceManager.GetString("ptVideoAlbumModifyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 视频专辑信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoAlbumShow {
            get {
                return ResourceManager.GetString("ptVideoAlbumShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以查看专辑信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoAlbumShowTip {
            get {
                return ResourceManager.GetString("ptVideoAlbumShowTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增视频分类 的本地化字符串。
        /// </summary>
        internal static string ptVideoClassAdd {
            get {
                return ResourceManager.GetString("ptVideoClassAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增、删除、编辑、查看视频分类 的本地化字符串。
        /// </summary>
        internal static string ptVideoClassAddTip {
            get {
                return ResourceManager.GetString("ptVideoClassAddTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 视频分类管理 的本地化字符串。
        /// </summary>
        internal static string ptVideoClassList {
            get {
                return ResourceManager.GetString("ptVideoClassList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增、删除、编辑、查看视频分类 的本地化字符串。
        /// </summary>
        internal static string ptVideoClassListTip {
            get {
                return ResourceManager.GetString("ptVideoClassListTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑视频分类 的本地化字符串。
        /// </summary>
        internal static string ptVideoClassModify {
            get {
                return ResourceManager.GetString("ptVideoClassModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑分类信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoClassModifyTip {
            get {
                return ResourceManager.GetString("ptVideoClassModifyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查看视频分类 的本地化字符串。
        /// </summary>
        internal static string ptVideoClassShow {
            get {
                return ResourceManager.GetString("ptVideoClassShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以查看分类信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoClassShowTip {
            get {
                return ResourceManager.GetString("ptVideoClassShowTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 视频信息管理 的本地化字符串。
        /// </summary>
        internal static string ptVideoList {
            get {
                return ResourceManager.GetString("ptVideoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增、删除、编辑、查看视频信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoListTip {
            get {
                return ResourceManager.GetString("ptVideoListTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑视频信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoModify {
            get {
                return ResourceManager.GetString("ptVideoModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoModifyTip {
            get {
                return ResourceManager.GetString("ptVideoModifyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 视频快速预览 的本地化字符串。
        /// </summary>
        internal static string ptVideoQuickPreview {
            get {
                return ResourceManager.GetString("ptVideoQuickPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查看视频信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoShow {
            get {
                return ResourceManager.GetString("ptVideoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以查看信息 的本地化字符串。
        /// </summary>
        internal static string ptVideoShowTip {
            get {
                return ResourceManager.GetString("ptVideoShowTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已发布 的本地化字符串。
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 推荐 的本地化字符串。
        /// </summary>
        internal static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 被屏蔽 的本地化字符串。
        /// </summary>
        internal static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 仅好友观看 的本地化字符串。
        /// </summary>
        internal static string SemiOpen {
            get {
                return ResourceManager.GetString("SemiOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 排序 的本地化字符串。
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 统计信息 的本地化字符串。
        /// </summary>
        internal static string StatisticalInfo {
            get {
                return ResourceManager.GetString("StatisticalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请先填写网址！ 的本地化字符串。
        /// </summary>
        internal static string TooltipFillWebsite {
            get {
                return ResourceManager.GetString("TooltipFillWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请先选择类型！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSwitchType {
            get {
                return ResourceManager.GetString("TooltipSwitchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请先上传视频！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSwitchVideo {
            get {
                return ResourceManager.GetString("TooltipSwitchVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您输入的视频播放页地址有误！ 的本地化字符串。
        /// </summary>
        internal static string TooltipVideoUrl {
            get {
                return ResourceManager.GetString("TooltipVideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 转码失败 的本地化字符串。
        /// </summary>
        internal static string TranscodingFail {
            get {
                return ResourceManager.GetString("TranscodingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 转码中 的本地化字符串。
        /// </summary>
        internal static string TurnCode {
            get {
                return ResourceManager.GetString("TurnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 视频 的本地化字符串。
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
