//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddPaymentMode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddPaymentMode() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AddPaymentMode", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 电子邮件地址的长度在200个字符以内 的本地化字符串。
        /// </summary>
        internal static string ErrorEmailLength {
            get {
                return ResourceManager.GetString("ErrorEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 支付手续费必须大于0 的本地化字符串。
        /// </summary>
        internal static string ErrorHandlingCharge {
            get {
                return ResourceManager.GetString("ErrorHandlingCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 支付手续费必须大于0 的本地化字符串。
        /// </summary>
        internal static string ErrorPayFee {
            get {
                return ResourceManager.GetString("ErrorPayFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未知错误 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_Create_UnKnowError {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_Create_UnKnowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已经添加了一个相同类型的支付接口 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_GatewayExists {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_GatewayExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 支付方式的数目已经超出系统设置的数目 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_OutofNumber {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_OutofNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已经存在一个相同的支付方式名称 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_PaymentNameExitis {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_PaymentNameExitis", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_lblReturn {
            get {
                return ResourceManager.GetString("IDS_FromField_lblReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 成功添加了一个支付方式 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_Create_Success {
            get {
                return ResourceManager.GetString("IDS_Message_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 从系统现有的支付接口类型中选择添加适合网站的支付方式 的本地化字符串。
        /// </summary>
        internal static string IDS_PageDesc {
            get {
                return ResourceManager.GetString("IDS_PageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加支付方式 的本地化字符串。
        /// </summary>
        internal static string IDS_PageTitle {
            get {
                return ResourceManager.GetString("IDS_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否允许使用此支付方式给账户在线充值 的本地化字符串。
        /// </summary>
        internal static string lblAllowRecharge {
            get {
                return ResourceManager.GetString("lblAllowRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否支持在线充值 的本地化字符串。
        /// </summary>
        internal static string lblOnlineRecharge {
            get {
                return ResourceManager.GetString("lblOnlineRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增、修改、删除支付方式管理 的本地化字符串。
        /// </summary>
        internal static string lblPaymentModes {
            get {
                return ResourceManager.GetString("lblPaymentModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改支付方式 的本地化字符串。
        /// </summary>
        internal static string ptEditPaymentMode {
            get {
                return ResourceManager.GetString("ptEditPaymentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 支付方式管理 的本地化字符串。
        /// </summary>
        internal static string ptPaymentModes {
            get {
                return ResourceManager.GetString("ptPaymentModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电子邮件地址的长度在200个字符以内 的本地化字符串。
        /// </summary>
        internal static string TooltipEmialAddressLength {
            get {
                return ResourceManager.GetString("TooltipEmialAddressLength", resourceCulture);
            }
        }
    }
}
