//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditPaymentMode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditPaymentMode() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EditPaymentMode", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string IDS_Button_Update {
            get {
                return ResourceManager.GetString("IDS_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 支付方式的数目已经超出系统设置的数目 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_OutofNumber {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_OutofNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已经存在一个相同的支付方式名称 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_PaymentNameExitis {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_PaymentNameExitis", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未知错误 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_Update_UnKnowError {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_Update_UnKnowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_lblReturn {
            get {
                return ResourceManager.GetString("IDS_FromField_lblReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 成功修改了当前支付方式 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_Update_Success {
            get {
                return ResourceManager.GetString("IDS_Message_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改支付方式的各项参数 的本地化字符串。
        /// </summary>
        internal static string IDS_PageDesc {
            get {
                return ResourceManager.GetString("IDS_PageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改支付方式 的本地化字符串。
        /// </summary>
        internal static string IDS_PageTitle {
            get {
                return ResourceManager.GetString("IDS_PageTitle", resourceCulture);
            }
        }
    }
}
