//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentModeView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentModeView() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PaymentModeView", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 显示顺序号必须是在1至65535之间的数字 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_DisplaySequence {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_DisplaySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 百分比 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_chkIsPercent {
            get {
                return ResourceManager.GetString("IDS_FormField_chkIsPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 手续费： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblCharge {
            get {
                return ResourceManager.GetString("IDS_FormField_lblCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 必填  系统列举出了此接口类型支持的所有货币类型，您需要在这些货币类型中选择网站接受支付的货币类型 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblCurrencyHelp {
            get {
                return ResourceManager.GetString("IDS_FormField_lblCurrencyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 支持交易货币： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblCurrencys {
            get {
                return ResourceManager.GetString("IDS_FormField_lblCurrencys", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 详细介绍 ： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblDescription {
            get {
                return ResourceManager.GetString("IDS_FormField_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 显示顺序号： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblDisplaySequence {
            get {
                return ResourceManager.GetString("IDS_FormField_lblDisplaySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商户邮件： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblEmailAddress {
            get {
                return ResourceManager.GetString("IDS_FormField_lblEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 接口类型： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblGateway {
            get {
                return ResourceManager.GetString("IDS_FormField_lblGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商户号： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblMerchantCode {
            get {
                return ResourceManager.GetString("IDS_FormField_lblMerchantCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 支付方式名称： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblName {
            get {
                return ResourceManager.GetString("IDS_FormField_lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 合作伙伴： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblPartner {
            get {
                return ResourceManager.GetString("IDS_FormField_lblPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商户密码： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblPassWord {
            get {
                return ResourceManager.GetString("IDS_FormField_lblPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第二密钥： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblSecondKey {
            get {
                return ResourceManager.GetString("IDS_FormField_lblSecondKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商户密钥： 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_lblSecretKey {
            get {
                return ResourceManager.GetString("IDS_FormField_lblSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择网关 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_nullToDisplay {
            get {
                return ResourceManager.GetString("IDS_FormField_nullToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入您的商户号对应的密码，此支付公司要求填写密码 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_PassWord_Description {
            get {
                return ResourceManager.GetString("IDS_FormField_PassWord_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置顾客选择此支付方式时需要额外支付的手续费，如果选中百分比，则表示支付手续费的金额根据订单金额按照设置的百分比收取，如果不需要顾客支付手续费，则设为0 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_Charge_Description {
            get {
                return ResourceManager.GetString("IDS_Message_Charge_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置顾客下订单选择支付方式时，此支付方式显示的位置 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_DisplaySequence_Description {
            get {
                return ResourceManager.GetString("IDS_Message_DisplaySequence_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商户号一般是您在支付公司注册的账号，您也可以登陆支付公司后按照说明查找您的商户号，长度限制在300个字符以内 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_MerchantCode_Description {
            get {
                return ResourceManager.GetString("IDS_Message_MerchantCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 支付方式名称的长度限制在50个字符以内 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_Name_Description {
            get {
                return ResourceManager.GetString("IDS_Message_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 在选择一个接口类型之前，必须具备一个在该支付公司注册过的账号，然后按照支付公司提供的账户信息填写此支付方式所需的信息，不同的接口类型要求填写的信息可能会不一样 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_PayInterface_Description {
            get {
                return ResourceManager.GetString("IDS_Message_PayInterface_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入支付方式名称 的本地化字符串。
        /// </summary>
        internal static string IDS_PaymentModeName_NotInput {
            get {
                return ResourceManager.GetString("IDS_PaymentModeName_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 支付方式名称长度超出范围 的本地化字符串。
        /// </summary>
        internal static string IDS_PaymentModeName_OutLength {
            get {
                return ResourceManager.GetString("IDS_PaymentModeName_OutLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 手续费设置有误，手续费只能是大于或等于零的数值 的本地化字符串。
        /// </summary>
        internal static string IDS_PaymentMode_Charge_Error {
            get {
                return ResourceManager.GetString("IDS_PaymentMode_Charge_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择当前商户支持的交易币种 的本地化字符串。
        /// </summary>
        internal static string IDS_PaymnetMode_Currency_NotSelect {
            get {
                return ResourceManager.GetString("IDS_PaymnetMode_Currency_NotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入商户号 的本地化字符串。
        /// </summary>
        internal static string IDS_PaymnetMode_MerchantCode_NotInput {
            get {
                return ResourceManager.GetString("IDS_PaymnetMode_MerchantCode_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入商户密码 的本地化字符串。
        /// </summary>
        internal static string IDS_PaymnetMode_Password_NotInput {
            get {
                return ResourceManager.GetString("IDS_PaymnetMode_Password_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 为了保证支付的安全性和真实性，很多支付公司都为商家提供了一个密钥并要求使用此密钥验证支付信息，也有的支付公司称之为校验码或验证码 的本地化字符串。
        /// </summary>
        internal static string IDS_PaymnetMode_SecondKey_Description {
            get {
                return ResourceManager.GetString("IDS_PaymnetMode_SecondKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入第二密钥 的本地化字符串。
        /// </summary>
        internal static string IDS_PaymnetMode_SecondKey_NotInput {
            get {
                return ResourceManager.GetString("IDS_PaymnetMode_SecondKey_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入商户密钥 的本地化字符串。
        /// </summary>
        internal static string IDS_PaymnetMode_SecretKey_NotInput {
            get {
                return ResourceManager.GetString("IDS_PaymnetMode_SecretKey_NotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请先选择一个支付接口 的本地化字符串。
        /// </summary>
        internal static string IDS_SelectPayInterface {
            get {
                return ResourceManager.GetString("IDS_SelectPayInterface", resourceCulture);
            }
        }
    }
}
