//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentModes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentModes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PaymentModes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 确定要删除选择的支付方式吗？ 的本地化字符串。
        /// </summary>
        internal static string IDS_Delete_Message {
            get {
                return ResourceManager.GetString("IDS_Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请先选择您要删除的支付方式名称 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_No_Check {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_No_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未知错误 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_UnKownError {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_UnKownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加支付方式 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_lblAddPaymentMode {
            get {
                return ResourceManager.GetString("IDS_FromField_lblAddPaymentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 显示顺序 的本地化字符串。
        /// </summary>
        internal static string IDS_Header_DisplaySequence {
            get {
                return ResourceManager.GetString("IDS_Header_DisplaySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 接口类型 的本地化字符串。
        /// </summary>
        internal static string IDS_Header_Gateway {
            get {
                return ResourceManager.GetString("IDS_Header_Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商户号 的本地化字符串。
        /// </summary>
        internal static string IDS_Header_merchantCode {
            get {
                return ResourceManager.GetString("IDS_Header_merchantCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 方式名称 的本地化字符串。
        /// </summary>
        internal static string IDS_Header_Name {
            get {
                return ResourceManager.GetString("IDS_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 成功删除了{0}个支付方式 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_Delete_Number {
            get {
                return ResourceManager.GetString("IDS_Message_Delete_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 成功删除了一个支付方式 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_Delete_Success {
            get {
                return ResourceManager.GetString("IDS_Message_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网站当前的所有支付方式，顾客在下订单的时候将从中选择一个支付方式 的本地化字符串。
        /// </summary>
        internal static string IDS_PageDesc {
            get {
                return ResourceManager.GetString("IDS_PageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 支付方式管理 的本地化字符串。
        /// </summary>
        internal static string IDS_PageTitle {
            get {
                return ResourceManager.GetString("IDS_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已经存在相同的支付方式名称 的本地化字符串。
        /// </summary>
        internal static string IDS_PaymentNameExitis {
            get {
                return ResourceManager.GetString("IDS_PaymentNameExitis", resourceCulture);
            }
        }
    }
}
