//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailSettings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EmailSettings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string IDM_btnChangeEmailSettings {
            get {
                return ResourceManager.GetString("IDM_btnChangeEmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 测试邮件设置 的本地化字符串。
        /// </summary>
        internal static string IDM_btnTestEmailSettings {
            get {
                return ResourceManager.GetString("IDM_btnTestEmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 测试邮件发送失败 的本地化字符串。
        /// </summary>
        internal static string IDM_btnTestEmailSettings_Click_Msg_NO {
            get {
                return ResourceManager.GetString("IDM_btnTestEmailSettings_Click_Msg_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 测试邮件发送成功，请到{0}查看邮件 的本地化字符串。
        /// </summary>
        internal static string IDM_btnTestEmailSettings_Click_Msg_OK {
            get {
                return ResourceManager.GetString("IDM_btnTestEmailSettings_Click_Msg_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 一般设置 的本地化字符串。
        /// </summary>
        internal static string IDM_EmailGeneralSettings {
            get {
                return ResourceManager.GetString("IDM_EmailGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置一次发送邮件的最大数量，设置为0表示不限制数量 的本地化字符串。
        /// </summary>
        internal static string IDM_help03 {
            get {
                return ResourceManager.GetString("IDM_help03", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SMTP服务器的地址，如新浪的SMTP服务器是smtp.sina.com.cn 的本地化字符串。
        /// </summary>
        internal static string IDM_help04 {
            get {
                return ResourceManager.GetString("IDM_help04", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置您在邮件服务器上注册的用户名。如果是普通邮箱为您的电子邮件地址的“@”符号前面的部分，如果是企业邮箱为整个邮箱 的本地化字符串。
        /// </summary>
        internal static string IDM_help07 {
            get {
                return ResourceManager.GetString("IDM_help07", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置您登陆邮箱的密码 的本地化字符串。
        /// </summary>
        internal static string IDM_help08 {
            get {
                return ResourceManager.GetString("IDM_help08", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请再输入一遍您登陆邮箱的密码 的本地化字符串。
        /// </summary>
        internal static string IDM_help082 {
            get {
                return ResourceManager.GetString("IDM_help082", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置SMTP服务器的端口号，一般默认都是25 的本地化字符串。
        /// </summary>
        internal static string IDM_help09 {
            get {
                return ResourceManager.GetString("IDM_help09", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置网站发送给客户邮件的电子邮件地址，电子邮件地址的长度在200个字符以内 的本地化字符串。
        /// </summary>
        internal static string IDM_help10 {
            get {
                return ResourceManager.GetString("IDM_help10", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SMTP邮箱： 的本地化字符串。
        /// </summary>
        internal static string IDM_lblAdminEmailAddress {
            get {
                return ResourceManager.GetString("IDM_lblAdminEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件编码格式： 的本地化字符串。
        /// </summary>
        internal static string IDM_lblEmailEncoding {
            get {
                return ResourceManager.GetString("IDM_lblEmailEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 一次发送数量限制： 的本地化字符串。
        /// </summary>
        internal static string IDM_lblEmailThrottle {
            get {
                return ResourceManager.GetString("IDM_lblEmailThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 安全连接(SSL)： 的本地化字符串。
        /// </summary>
        internal static string IDM_lblSmtpEnableSsl {
            get {
                return ResourceManager.GetString("IDM_lblSmtpEnableSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SMTP服务器端口： 的本地化字符串。
        /// </summary>
        internal static string IDM_lblSmtpPortNumber {
            get {
                return ResourceManager.GetString("IDM_lblSmtpPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SMTP服务器： 的本地化字符串。
        /// </summary>
        internal static string IDM_lblSmtpServer {
            get {
                return ResourceManager.GetString("IDM_lblSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SMTP用户密码： 的本地化字符串。
        /// </summary>
        internal static string IDM_lblSmtpServerPassword {
            get {
                return ResourceManager.GetString("IDM_lblSmtpServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 重复用户密码： 的本地化字符串。
        /// </summary>
        internal static string IDM_lblSmtpServerPassword2 {
            get {
                return ResourceManager.GetString("IDM_lblSmtpServerPassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SMTP用户名： 的本地化字符串。
        /// </summary>
        internal static string IDM_lblSmtpServerUserName {
            get {
                return ResourceManager.GetString("IDM_lblSmtpServerUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件服务器登陆设置 的本地化字符串。
        /// </summary>
        internal static string IDM_SMTPLoginInfo {
            get {
                return ResourceManager.GetString("IDM_SMTPLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已成功修改邮件发送设置 的本地化字符串。
        /// </summary>
        internal static string IDS_btnChangeEmailSettings_Click_Msg_OK {
            get {
                return ResourceManager.GetString("IDS_btnChangeEmailSettings_Click_Msg_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电子邮件地址格式不正确，请输入正确的电子邮件地址 的本地化字符串。
        /// </summary>
        internal static string IDS_EmailAddress_Error {
            get {
                return ResourceManager.GetString("IDS_EmailAddress_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 一次发送数量限制在10000以下 的本地化字符串。
        /// </summary>
        internal static string IDS_EmailThrottle_Error {
            get {
                return ResourceManager.GetString("IDS_EmailThrottle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置此SMTP服务器是否需要安全连接，如果使用安全连接，SMTP的端口号则可能和默认的端口号不一样 的本地化字符串。
        /// </summary>
        internal static string IDS_help01 {
            get {
                return ResourceManager.GetString("IDS_help01", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 一次发送邮件的最大数量只能是数字 的本地化字符串。
        /// </summary>
        internal static string IDS_Invalid_EmailThrottle_NotNumber {
            get {
                return ResourceManager.GetString("IDS_Invalid_EmailThrottle_NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件服务器的端口号只能是数字 的本地化字符串。
        /// </summary>
        internal static string IDS_Invalid_SmtpPortNumber_NotNumber {
            get {
                return ResourceManager.GetString("IDS_Invalid_SmtpPortNumber_NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 两次输入的密码不一致 的本地化字符串。
        /// </summary>
        internal static string IDS_Invalid_SmtpServerPassword_NotComp {
            get {
                return ResourceManager.GetString("IDS_Invalid_SmtpServerPassword_NotComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入邮件服务器登陆名 的本地化字符串。
        /// </summary>
        internal static string IDS_Invalid_SmtpServerUserName_FormatError {
            get {
                return ResourceManager.GetString("IDS_Invalid_SmtpServerUserName_FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请正确配置您的邮件服务器信息，系统将使用这些信息自动为客户发送邮件 的本地化字符串。
        /// </summary>
        internal static string IDS_PageDesc {
            get {
                return ResourceManager.GetString("IDS_PageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件发送设置 的本地化字符串。
        /// </summary>
        internal static string IDS_PageTiTle {
            get {
                return ResourceManager.GetString("IDS_PageTiTle", resourceCulture);
            }
        }
    }
}
