//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class installerdefault {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal installerdefault() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.installerdefault", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 接受 的本地化字符串。
        /// </summary>
        internal static string IDS_Button_Agree {
            get {
                return ResourceManager.GetString("IDS_Button_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 不接受 的本地化字符串。
        /// </summary>
        internal static string IDS_Button_NO {
            get {
                return ResourceManager.GetString("IDS_Button_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 &lt;textarea name=&quot;textarea&quot; cols=&quot;65&quot; rows=&quot;13&quot;&gt;请仔细阅读以下最终用户许可协议（《协议》）。一旦安装 或使用随此《协议》提供的软件（“软件”），即表明您同 意本《协议》的各项条款。如果您不同意，则不要使用“软 件”。 
        ///  
        ///请仔细阅读以下最终用户许可协议（《协议》）。一旦安装或使用随此《协议》提供的软件（“软件”），即表明您同意本《协议》的各项条款。如果您不同意，则不要使用“软件”。 
        ///  
        ///本“软件产品”受中华人民共和国著作权法和其它知识产权法及条约的保护。本“软件产品”只是提供使用许可协议，而非出售。 
        ///  
        ///软件产品许可协议 
        ///  
        ///1．许可协议的授予 
        ///本《协议》授予您下列权利：
        ///本“软件产品”只允许在一台计算机上使用，不允许在两台或两台以上的计算机上同时使用。
        ///数据库可以放至另一台计算机上使用。 
        ///  
        ///2．其它权利和限制说明 
        ///对反相工程（Reverse Engineering）、反编译（Decompilation）、反汇编（Disassembly）的限制：您不得对本“软件产品”进行反相工程（reverse engineer [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_Area {
            get {
                return ResourceManager.GetString("IDS_FormField_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 专业B2C在线商城 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_Label1 {
            get {
                return ResourceManager.GetString("IDS_FormField_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 为企业发展赢得先机! 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_Label2 {
            get {
                return ResourceManager.GetString("IDS_FormField_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 软件最终用户许可协议 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_Label3 {
            get {
                return ResourceManager.GetString("IDS_FormField_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 YSWL  © 2012 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_Label4 {
            get {
                return ResourceManager.GetString("IDS_FormField_Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 YSWL 2012 安装向导 的本地化字符串。
        /// </summary>
        internal static string IDS_PageTitle {
            get {
                return ResourceManager.GetString("IDS_PageTitle", resourceCulture);
            }
        }
    }
}
