//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class installerstep {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal installerstep() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.installerstep", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 下载配置文件 的本地化字符串。
        /// </summary>
        internal static string IDS_Button_btnDownConfig {
            get {
                return ResourceManager.GetString("IDS_Button_btnDownConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 两次密码不一致 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_comPassword {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_comPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库登录名不能为空 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_dbLogin {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_dbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库名不能为空 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_dbName {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_dbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库登录密码不能为空 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_dbPassword {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_dbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件地址不能为空 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_EmailNotNull {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_EmailNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 没有找到数据库架构脚本文件 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_FileExitis {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_FileExitis", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_Password {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库服务器地址不能为空 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_Server {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_UserNotNull {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_UserNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库登录名 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_dbLogin {
            get {
                return ResourceManager.GetString("IDS_FormField_dbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库名称 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_dbName {
            get {
                return ResourceManager.GetString("IDS_FormField_dbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库登录密码 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_dbPassword {
            get {
                return ResourceManager.GetString("IDS_FormField_dbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第一步：数据库连接信息设置 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_FirstStep {
            get {
                return ResourceManager.GetString("IDS_FormField_FirstStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_Port {
            get {
                return ResourceManager.GetString("IDS_FormField_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库服务器地址 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_Server {
            get {
                return ResourceManager.GetString("IDS_FormField_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 相关设置信息请咨询虚拟主机提供商,或者与联系我们的客服 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_SetpDesciption {
            get {
                return ResourceManager.GetString("IDS_FormField_SetpDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 相关设置信息请咨询虚拟主机提供商,或者与联系我们的客服. 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_Step2Desciption {
            get {
                return ResourceManager.GetString("IDS_FormField_Step2Desciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第二步：后台信息设置 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_StepSeconed {
            get {
                return ResourceManager.GetString("IDS_FormField_StepSeconed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 重复密码 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_ComPassword {
            get {
                return ResourceManager.GetString("IDS_FromField_ComPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 默认货币 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_Currency {
            get {
                return ResourceManager.GetString("IDS_FromField_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否添加演示数据 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_DefalutData {
            get {
                return ResourceManager.GetString("IDS_FromField_DefalutData", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件地址 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_Email {
            get {
                return ResourceManager.GetString("IDS_FromField_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加演示数据 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_ISDefalut {
            get {
                return ResourceManager.GetString("IDS_FromField_ISDefalut", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_Password {
            get {
                return ResourceManager.GetString("IDS_FromField_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 站点描述 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_SiteDescription {
            get {
                return ResourceManager.GetString("IDS_FromField_SiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 站点名称 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_SiteName {
            get {
                return ResourceManager.GetString("IDS_FromField_SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_UserName {
            get {
                return ResourceManager.GetString("IDS_FromField_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 这些数据用于演示系统功能而设置的,在实际应用的时候可以将其删除 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_Zhushi {
            get {
                return ResourceManager.GetString("IDS_FromField_Zhushi", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 注意：您还需要继续以下操作来完成安装 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_Create_Error {
            get {
                return ResourceManager.GetString("IDS_Message_Create_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 感谢您使用YSWL商城系统 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_gx {
            get {
                return ResourceManager.GetString("IDS_Message_gx", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 安装完成 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_InstallerEnd {
            get {
                return ResourceManager.GetString("IDS_Message_InstallerEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 由于系统没有直接修改配置文件的权限，您需要先下载配置文件到您本地的机器上，然后再上传到网站根目录。 的本地化字符串。
        /// </summary>
        internal static string IDS_Message_Update_Config {
            get {
                return ResourceManager.GetString("IDS_Message_Update_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择您需要的操作 的本地化字符串。
        /// </summary>
        internal static string IDS_Select_Option {
            get {
                return ResourceManager.GetString("IDS_Select_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 &gt;&gt;进入后台 的本地化字符串。
        /// </summary>
        internal static string IDS_ToAdmin {
            get {
                return ResourceManager.GetString("IDS_ToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 &gt;&gt;进入前台 的本地化字符串。
        /// </summary>
        internal static string IDS_ToDefault {
            get {
                return ResourceManager.GetString("IDS_ToDefault", resourceCulture);
            }
        }
    }
}
