//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 员工 的本地化字符串。
        /// </summary>
        internal static string drpListUU {
            get {
                return ResourceManager.GetString("drpListUU", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 消息内容不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorContentNotNull {
            get {
                return ResourceManager.GetString("ErrorContentNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更新时间格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorLastDateForm {
            get {
                return ResourceManager.GetString("ErrorLastDateForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 收件人ID格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorReciveID {
            get {
                return ResourceManager.GetString("ErrorReciveID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送时间格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorSendDateForm {
            get {
                return ResourceManager.GetString("ErrorSendDateForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发件人ID格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorSendID {
            get {
                return ResourceManager.GetString("ErrorSendID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 消息主题不能为空! 的本地化字符串。
        /// </summary>
        internal static string ErrorTitleNotNull {
            get {
                return ResourceManager.GetString("ErrorTitleNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发件人 的本地化字符串。
        /// </summary>
        internal static string fieldAddresserId {
            get {
                return ResourceManager.GetString("fieldAddresserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 员工编码 的本地化字符串。
        /// </summary>
        internal static string fieldEmployeeID {
            get {
                return ResourceManager.GetString("fieldEmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否已读 的本地化字符串。
        /// </summary>
        internal static string fieldIsRead {
            get {
                return ResourceManager.GetString("fieldIsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更新时间 的本地化字符串。
        /// </summary>
        internal static string fieldLastTime {
            get {
                return ResourceManager.GetString("fieldLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 消息内容 的本地化字符串。
        /// </summary>
        internal static string fieldPublishContent {
            get {
                return ResourceManager.GetString("fieldPublishContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送日期 的本地化字符串。
        /// </summary>
        internal static string fieldPublishDate {
            get {
                return ResourceManager.GetString("fieldPublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信息编号 的本地化字符串。
        /// </summary>
        internal static string fieldReceiveMessageId {
            get {
                return ResourceManager.GetString("fieldReceiveMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 收件人 的本地化字符串。
        /// </summary>
        internal static string fieldRecipient {
            get {
                return ResourceManager.GetString("fieldRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发信息编号 的本地化字符串。
        /// </summary>
        internal static string fieldSendMessageId {
            get {
                return ResourceManager.GetString("fieldSendMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 消息主题 的本地化字符串。
        /// </summary>
        internal static string fieldTitle {
            get {
                return ResourceManager.GetString("fieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择用户 的本地化字符串。
        /// </summary>
        internal static string lblChoseUser {
            get {
                return ResourceManager.GetString("lblChoseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对收件箱进行管理 的本地化字符串。
        /// </summary>
        internal static string lblInboxList {
            get {
                return ResourceManager.GetString("lblInboxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 详细短信息 的本地化字符串。
        /// </summary>
        internal static string lblMessageShow {
            get {
                return ResourceManager.GetString("lblMessageShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对发件箱里的信息进行管理 的本地化字符串。
        /// </summary>
        internal static string lblOutboxList {
            get {
                return ResourceManager.GetString("lblOutboxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发信息 的本地化字符串。
        /// </summary>
        internal static string lblSendMessage {
            get {
                return ResourceManager.GetString("lblSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以选择给所有用户,指定等级用户或单个用户发送站内消息。 的本地化字符串。
        /// </summary>
        internal static string lblSendMessageSelectUser {
            get {
                return ResourceManager.GetString("lblSendMessageSelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以向网站的用户发送短消息 的本地化字符串。
        /// </summary>
        internal static string lblSendMessageToUser {
            get {
                return ResourceManager.GetString("lblSendMessageToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑信息 的本地化字符串。
        /// </summary>
        internal static string ptEditInformation {
            get {
                return ResourceManager.GetString("ptEditInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 收件箱管理 的本地化字符串。
        /// </summary>
        internal static string ptInboxList {
            get {
                return ResourceManager.GetString("ptInboxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信息详情 的本地化字符串。
        /// </summary>
        internal static string ptMessageShow {
            get {
                return ResourceManager.GetString("ptMessageShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发件箱管理 的本地化字符串。
        /// </summary>
        internal static string ptOutboxList {
            get {
                return ResourceManager.GetString("ptOutboxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送短消息 的本地化字符串。
        /// </summary>
        internal static string ptSendMessage {
            get {
                return ResourceManager.GetString("ptSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择用户发送站内消息 的本地化字符串。
        /// </summary>
        internal static string ptSendMessageSelectUser {
            get {
                return ResourceManager.GetString("ptSendMessageSelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否生效 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发生失败！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSendFail {
            get {
                return ResourceManager.GetString("TooltipSendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSendSucceed {
            get {
                return ResourceManager.GetString("TooltipSendSucceed", resourceCulture);
            }
        }
    }
}
