//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsEntryForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsEntryForm() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MsEntryForm", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 用户姓名不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorNameNotNull {
            get {
                return ResourceManager.GetString("ErrorNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注信息过长，最多允许300个字符！ 的本地化字符串。
        /// </summary>
        internal static string ErrorRemarkoverlength {
            get {
                return ResourceManager.GetString("ErrorRemarkoverlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司地址 的本地化字符串。
        /// </summary>
        internal static string lblCompanyAddress {
            get {
                return ResourceManager.GetString("lblCompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 家庭地址 的本地化字符串。
        /// </summary>
        internal static string lblHouseAddress {
            get {
                return ResourceManager.GetString("lblHouseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增报名信息 的本地化字符串。
        /// </summary>
        internal static string lblMsEntryFormAdd {
            get {
                return ResourceManager.GetString("lblMsEntryFormAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增、修改、删除报名用户 的本地化字符串。
        /// </summary>
        internal static string lblMsEntryFormList {
            get {
                return ResourceManager.GetString("lblMsEntryFormList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑报名用户信息 的本地化字符串。
        /// </summary>
        internal static string lblMsEntryModify {
            get {
                return ResourceManager.GetString("lblMsEntryModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查看报名用户详细信息 的本地化字符串。
        /// </summary>
        internal static string lblMsEntryShow {
            get {
                return ResourceManager.GetString("lblMsEntryShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户姓名 的本地化字符串。
        /// </summary>
        internal static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加报名信息 的本地化字符串。
        /// </summary>
        internal static string ptMsEntryFormAdd {
            get {
                return ResourceManager.GetString("ptMsEntryFormAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 报名用户管理 的本地化字符串。
        /// </summary>
        internal static string ptMsEntryFormList {
            get {
                return ResourceManager.GetString("ptMsEntryFormList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑报名用户信息 的本地化字符串。
        /// </summary>
        internal static string ptMsEntryModify {
            get {
                return ResourceManager.GetString("ptMsEntryModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 报名用户详细信息 的本地化字符串。
        /// </summary>
        internal static string ptMsEntryShow {
            get {
                return ResourceManager.GetString("ptMsEntryShow", resourceCulture);
            }
        }
    }
}
