//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsEnterprise {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsEnterprise() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MsEnterprise", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 私营独资企业 的本地化字符串。
        /// </summary>
        internal static string DrpListEnterprises {
            get {
                return ResourceManager.GetString("DrpListEnterprises", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 个体工商 的本地化字符串。
        /// </summary>
        internal static string DrpListIndividual {
            get {
                return ResourceManager.GetString("DrpListIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 国营企业 的本地化字符串。
        /// </summary>
        internal static string DrpListStateowned {
            get {
                return ResourceManager.GetString("DrpListStateowned", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 *公司法人不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorArtiPerson {
            get {
                return ResourceManager.GetString("ErrorArtiPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 *企业分类不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorEnteClassID {
            get {
                return ResourceManager.GetString("ErrorEnteClassID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 *企业等级不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorEnteRank {
            get {
                return ResourceManager.GetString("ErrorEnteRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 *企业名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorEnterpriseName {
            get {
                return ResourceManager.GetString("ErrorEnterpriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 *成立时间不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorEstablishedDate {
            get {
                return ResourceManager.GetString("ErrorEstablishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业介绍不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorIntroductionNotNull {
            get {
                return ResourceManager.GetString("ErrorIntroductionNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 成立时间格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorlblEstablishedDate {
            get {
                return ResourceManager.GetString("ErrorlblEstablishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择省/市！ 的本地化字符串。
        /// </summary>
        internal static string ErrorRegionID {
            get {
                return ResourceManager.GetString("ErrorRegionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 *注册资本不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorRegisteredCapital {
            get {
                return ResourceManager.GetString("ErrorRegisteredCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 *用户名不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorUserName {
            get {
                return ResourceManager.GetString("ErrorUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 代理商ID 的本地化字符串。
        /// </summary>
        internal static string fieldAgentID {
            get {
                return ResourceManager.GetString("fieldAgentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建日期 的本地化字符串。
        /// </summary>
        internal static string fieldCreatedDate {
            get {
                return ResourceManager.GetString("fieldCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建用户 的本地化字符串。
        /// </summary>
        internal static string fieldCreatedUserID {
            get {
                return ResourceManager.GetString("fieldCreatedUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更新日期 的本地化字符串。
        /// </summary>
        internal static string fieldUpdatedDate {
            get {
                return ResourceManager.GetString("fieldUpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更新用户 的本地化字符串。
        /// </summary>
        internal static string fieldUpdatedUserID {
            get {
                return ResourceManager.GetString("fieldUpdatedUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 开户银行 的本地化字符串。
        /// </summary>
        internal static string lblAccountBank {
            get {
                return ResourceManager.GetString("lblAccountBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 账号信息 的本地化字符串。
        /// </summary>
        internal static string lblAccountInfo {
            get {
                return ResourceManager.GetString("lblAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 详细地址 的本地化字符串。
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 法人 的本地化字符串。
        /// </summary>
        internal static string lblArtiPerson {
            get {
                return ResourceManager.GetString("lblArtiPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 手机 的本地化字符串。
        /// </summary>
        internal static string lblCellPhone {
            get {
                return ResourceManager.GetString("lblCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系人 的本地化字符串。
        /// </summary>
        internal static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系邮箱 的本地化字符串。
        /// </summary>
        internal static string lblContactMail {
            get {
                return ResourceManager.GetString("lblContactMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业分类 的本地化字符串。
        /// </summary>
        internal static string lblEnteClassID {
            get {
                return ResourceManager.GetString("lblEnteClassID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业等级 的本地化字符串。
        /// </summary>
        internal static string lblEnteRank {
            get {
                return ResourceManager.GetString("lblEnteRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业编号 的本地化字符串。
        /// </summary>
        internal static string lblEnterpriseID {
            get {
                return ResourceManager.GetString("lblEnterpriseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业管理 的本地化字符串。
        /// </summary>
        internal static string lblEnterpriseList {
            get {
                return ResourceManager.GetString("lblEnterpriseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业名称 的本地化字符串。
        /// </summary>
        internal static string lblEnterpriseName {
            get {
                return ResourceManager.GetString("lblEnterpriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户角色设置 的本地化字符串。
        /// </summary>
        internal static string lblEnterpriseRole {
            get {
                return ResourceManager.GetString("lblEnterpriseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业详细信息 的本地化字符串。
        /// </summary>
        internal static string lblEnterpriseShow {
            get {
                return ResourceManager.GetString("lblEnterpriseShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 注册地 的本地化字符串。
        /// </summary>
        internal static string lblEstablishedCity {
            get {
                return ResourceManager.GetString("lblEstablishedCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 成立时间 的本地化字符串。
        /// </summary>
        internal static string lblEstablishedDate {
            get {
                return ResourceManager.GetString("lblEstablishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 传真 的本地化字符串。
        /// </summary>
        internal static string lblFax {
            get {
                return ResourceManager.GetString("lblFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string lblHomePage {
            get {
                return ResourceManager.GetString("lblHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业介绍 的本地化字符串。
        /// </summary>
        internal static string lblIntroduction {
            get {
                return ResourceManager.GetString("lblIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 营业执照 的本地化字符串。
        /// </summary>
        internal static string lblLicense {
            get {
                return ResourceManager.GetString("lblLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 MSN 的本地化字符串。
        /// </summary>
        internal static string lblMSN {
            get {
                return ResourceManager.GetString("lblMSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮编 的本地化字符串。
        /// </summary>
        internal static string lblPostCode {
            get {
                return ResourceManager.GetString("lblPostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 QQ 的本地化字符串。
        /// </summary>
        internal static string lblQQ {
            get {
                return ResourceManager.GetString("lblQQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 省/市 的本地化字符串。
        /// </summary>
        internal static string lblRegionID {
            get {
                return ResourceManager.GetString("lblRegionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 注册资本 的本地化字符串。
        /// </summary>
        internal static string lblRegisteredCapital {
            get {
                return ResourceManager.GetString("lblRegisteredCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string lblRemark {
            get {
                return ResourceManager.GetString("lblRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客服电话 的本地化字符串。
        /// </summary>
        internal static string lblServicePhone {
            get {
                return ResourceManager.GetString("lblServicePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置推荐 的本地化字符串。
        /// </summary>
        internal static string lblSetRecommend {
            get {
                return ResourceManager.GetString("lblSetRecommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置可分配角色 的本地化字符串。
        /// </summary>
        internal static string lblSetRole {
            get {
                return ResourceManager.GetString("lblSetRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 税务登记 的本地化字符串。
        /// </summary>
        internal static string lblTaxRegistration {
            get {
                return ResourceManager.GetString("lblTaxRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string lblTelPhone {
            get {
                return ResourceManager.GetString("lblTelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加企业 的本地化字符串。
        /// </summary>
        internal static string ptAddEnterprise {
            get {
                return ResourceManager.GetString("ptAddEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业列表 的本地化字符串。
        /// </summary>
        internal static string ptEnterpriseList {
            get {
                return ResourceManager.GetString("ptEnterpriseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑企业信息 的本地化字符串。
        /// </summary>
        internal static string ptEnterpriseModif {
            get {
                return ResourceManager.GetString("ptEnterpriseModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业信息页 的本地化字符串。
        /// </summary>
        internal static string ptEnterpriseShow {
            get {
                return ResourceManager.GetString("ptEnterpriseShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司性质 的本地化字符串。
        /// </summary>
        internal static string ptEnterpriseType {
            get {
                return ResourceManager.GetString("ptEnterpriseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你确认要删除吗？删除企业的同时，和企业相关联的用户也同时删除！ 的本地化字符串。
        /// </summary>
        internal static string TooltipDeleteUser {
            get {
                return ResourceManager.GetString("TooltipDeleteUser", resourceCulture);
            }
        }
    }
}
