//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Poll {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Poll() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Poll", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 编辑题目 的本地化字符串。
        /// </summary>
        internal static string EditTopic {
            get {
                return ResourceManager.GetString("EditTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 问卷说明不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorFormsExplainNull {
            get {
                return ResourceManager.GetString("ErrorFormsExplainNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 问卷名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorFormsNameNull {
            get {
                return ResourceManager.GetString("ErrorFormsNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 没有数据！！ 的本地化字符串。
        /// </summary>
        internal static string ErrorNoData {
            get {
                return ResourceManager.GetString("ErrorNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该选项已经存在！ 的本地化字符串。
        /// </summary>
        internal static string ErrorOptionsExists {
            get {
                return ResourceManager.GetString("ErrorOptionsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选项名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorOptionsNotNull {
            get {
                return ResourceManager.GetString("ErrorOptionsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该题目已经存在！ 的本地化字符串。
        /// </summary>
        internal static string ErrorTopicExists {
            get {
                return ResourceManager.GetString("ErrorTopicExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 项目 的本地化字符串。
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 多选 的本地化字符串。
        /// </summary>
        internal static string lblCheck {
            get {
                return ResourceManager.GetString("lblCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 默认选中 的本地化字符串。
        /// </summary>
        internal static string lblDefaultCheched {
            get {
                return ResourceManager.GetString("lblDefaultCheched", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑选项 的本地化字符串。
        /// </summary>
        internal static string lblEditingOptions {
            get {
                return ResourceManager.GetString("lblEditingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 填写反馈 的本地化字符串。
        /// </summary>
        internal static string lblFeedBack {
            get {
                return ResourceManager.GetString("lblFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以增加问卷 的本地化字符串。
        /// </summary>
        internal static string lblFormsAdd {
            get {
                return ResourceManager.GetString("lblFormsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 问卷说明 的本地化字符串。
        /// </summary>
        internal static string lblFormsExplain {
            get {
                return ResourceManager.GetString("lblFormsExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 问卷编号 的本地化字符串。
        /// </summary>
        internal static string lblFormsID {
            get {
                return ResourceManager.GetString("lblFormsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对问卷进行管理 的本地化字符串。
        /// </summary>
        internal static string lblFormsIndex {
            get {
                return ResourceManager.GetString("lblFormsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 问卷名称 的本地化字符串。
        /// </summary>
        internal static string lblFormsName {
            get {
                return ResourceManager.GetString("lblFormsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否选中 的本地化字符串。
        /// </summary>
        internal static string lblIsChecked {
            get {
                return ResourceManager.GetString("lblIsChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选项 的本地化字符串。
        /// </summary>
        internal static string lblOption {
            get {
                return ResourceManager.GetString("lblOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以进行增加选项操作 的本地化字符串。
        /// </summary>
        internal static string lblOptionsAdd {
            get {
                return ResourceManager.GetString("lblOptionsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 共有 的本地化字符串。
        /// </summary>
        internal static string lblOptionsCommon {
            get {
                return ResourceManager.GetString("lblOptionsCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以增加题目 的本地化字符串。
        /// </summary>
        internal static string lblOptionsIndex {
            get {
                return ResourceManager.GetString("lblOptionsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选项名称 的本地化字符串。
        /// </summary>
        internal static string lblOptionsName {
            get {
                return ResourceManager.GetString("lblOptionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 的选项设计 的本地化字符串。
        /// </summary>
        internal static string lblOptionsQuestions {
            get {
                return ResourceManager.GetString("lblOptionsQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以查看投票 的本地化字符串。
        /// </summary>
        internal static string lblOptionsShow {
            get {
                return ResourceManager.GetString("lblOptionsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以查看问卷投票结果 的本地化字符串。
        /// </summary>
        internal static string lblOptionsShowCount {
            get {
                return ResourceManager.GetString("lblOptionsShowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 人参加，合计投票 的本地化字符串。
        /// </summary>
        internal static string lblOptionsTotal {
            get {
                return ResourceManager.GetString("lblOptionsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 人参与投票，参与本问卷投票 的本地化字符串。
        /// </summary>
        internal static string lblParticipation {
            get {
                return ResourceManager.GetString("lblParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户投票结果 的本地化字符串。
        /// </summary>
        internal static string lblPollResults {
            get {
                return ResourceManager.GetString("lblPollResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 问卷 的本地化字符串。
        /// </summary>
        internal static string lblQuestionnaire {
            get {
                return ResourceManager.GetString("lblQuestionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 单选 的本地化字符串。
        /// </summary>
        internal static string lblRadio {
            get {
                return ResourceManager.GetString("lblRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择的是： 的本地化字符串。
        /// </summary>
        internal static string lblSelected {
            get {
                return ResourceManager.GetString("lblSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 题目标题 的本地化字符串。
        /// </summary>
        internal static string lblTopicsTitle {
            get {
                return ResourceManager.GetString("lblTopicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 题目类型 的本地化字符串。
        /// </summary>
        internal static string lblTopicsType {
            get {
                return ResourceManager.GetString("lblTopicsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 共有注册用户 的本地化字符串。
        /// </summary>
        internal static string lblTotalOfUsers {
            get {
                return ResourceManager.GetString("lblTotalOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对投票用户进行管理 的本地化字符串。
        /// </summary>
        internal static string lblUsersList {
            get {
                return ResourceManager.GetString("lblUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似  请填写要在前台展示的问卷编号 的本地化字符串。
        /// </summary>
        internal static string lblWriteFormsID {
            get {
                return ResourceManager.GetString("lblWriteFormsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 投票数 的本地化字符串。
        /// </summary>
        internal static string NumberOfVotes {
            get {
                return ResourceManager.GetString("NumberOfVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 投票统计 的本地化字符串。
        /// </summary>
        internal static string OptionsStatistics {
            get {
                return ResourceManager.GetString("OptionsStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 人 的本地化字符串。
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电话/邮箱 的本地化字符串。
        /// </summary>
        internal static string PhoneOrEmial {
            get {
                return ResourceManager.GetString("PhoneOrEmial", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 票数 的本地化字符串。
        /// </summary>
        internal static string PollCount {
            get {
                return ResourceManager.GetString("PollCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 比例 的本地化字符串。
        /// </summary>
        internal static string Proportion {
            get {
                return ResourceManager.GetString("Proportion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加问卷 的本地化字符串。
        /// </summary>
        internal static string ptFormsAdd {
            get {
                return ResourceManager.GetString("ptFormsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 问卷管理 的本地化字符串。
        /// </summary>
        internal static string ptFormsIndex {
            get {
                return ResourceManager.GetString("ptFormsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑问卷 的本地化字符串。
        /// </summary>
        internal static string ptFormsModify {
            get {
                return ResourceManager.GetString("ptFormsModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加选项 的本地化字符串。
        /// </summary>
        internal static string ptOptionsAdd {
            get {
                return ResourceManager.GetString("ptOptionsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加题目 的本地化字符串。
        /// </summary>
        internal static string ptOptionsIndex {
            get {
                return ResourceManager.GetString("ptOptionsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查看投票 的本地化字符串。
        /// </summary>
        internal static string ptOptionsShow {
            get {
                return ResourceManager.GetString("ptOptionsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 问卷投票结果 的本地化字符串。
        /// </summary>
        internal static string ptOptionsShowCount {
            get {
                return ResourceManager.GetString("ptOptionsShowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 投票用户管理 的本地化字符串。
        /// </summary>
        internal static string ptUsersList {
            get {
                return ResourceManager.GetString("ptUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提示：网站投票使用地址为 的本地化字符串。
        /// </summary>
        internal static string TooltipUrl {
            get {
                return ResourceManager.GetString("TooltipUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查看结果 的本地化字符串。
        /// </summary>
        internal static string ViewResults {
            get {
                return ResourceManager.GetString("ViewResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 票 的本地化字符串。
        /// </summary>
        internal static string Votes {
            get {
                return ResourceManager.GetString("Votes", resourceCulture);
            }
        }
    }
}
