//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteSetting() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteSetting", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 内容评论 的本地化字符串。
        /// </summary>
        internal static string ContentComments {
            get {
                return ResourceManager.GetString("ContentComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorContentNotNull {
            get {
                return ResourceManager.GetString("ErrorContentNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发布时间格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorDateFormat {
            get {
                return ResourceManager.GetString("ErrorDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 父评论格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorParentComment {
            get {
                return ResourceManager.GetString("ErrorParentComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发布人格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorPublisherFormat {
            get {
                return ResourceManager.GetString("ErrorPublisherFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 回复数格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorReplyCount {
            get {
                return ResourceManager.GetString("ErrorReplyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主题格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorThemeFormat {
            get {
                return ResourceManager.GetString("ErrorThemeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 TypeID格式错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorTypeIDFormat {
            get {
                return ResourceManager.GetString("ErrorTypeIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 审核状态 的本地化字符串。
        /// </summary>
        internal static string lblApprovalStatus {
            get {
                return ResourceManager.GetString("lblApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对网站的评论进行管理 的本地化字符串。
        /// </summary>
        internal static string lblCommentList {
            get {
                return ResourceManager.GetString("lblCommentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string lblCommentTheme {
            get {
                return ResourceManager.GetString("lblCommentTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 联系人 的本地化字符串。
        /// </summary>
        internal static string lblContacts {
            get {
                return ResourceManager.GetString("lblContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以设置网站敏感词 的本地化字符串。
        /// </summary>
        internal static string lblFilterWord {
            get {
                return ResourceManager.GetString("lblFilterWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 过滤敏感字列表 的本地化字符串。
        /// </summary>
        internal static string lblFilterWordList {
            get {
                return ResourceManager.GetString("lblFilterWordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增友情链接 的本地化字符串。
        /// </summary>
        internal static string lblFriendlyLink {
            get {
                return ResourceManager.GetString("lblFriendlyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 友情链接编号 的本地化字符串。
        /// </summary>
        internal static string lblFriendlyLinkID {
            get {
                return ResourceManager.GetString("lblFriendlyLinkID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增、修改、删除友情链接 的本地化字符串。
        /// </summary>
        internal static string lblFriendlyLinkList {
            get {
                return ResourceManager.GetString("lblFriendlyLinkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以修改友情链接 的本地化字符串。
        /// </summary>
        internal static string lblFriendlyLinkModify {
            get {
                return ResourceManager.GetString("lblFriendlyLinkModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 友情链接查看 的本地化字符串。
        /// </summary>
        internal static string lblFriendlyLinkShow {
            get {
                return ResourceManager.GetString("lblFriendlyLinkShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片高度 的本地化字符串。
        /// </summary>
        internal static string lblImgHeight {
            get {
                return ResourceManager.GetString("lblImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片链接 的本地化字符串。
        /// </summary>
        internal static string lblImgLink {
            get {
                return ResourceManager.GetString("lblImgLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片地址 的本地化字符串。
        /// </summary>
        internal static string lblImgUrl {
            get {
                return ResourceManager.GetString("lblImgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片宽度 的本地化字符串。
        /// </summary>
        internal static string lblImgWidth {
            get {
                return ResourceManager.GetString("lblImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否显示 的本地化字符串。
        /// </summary>
        internal static string lblIsDisplay {
            get {
                return ResourceManager.GetString("lblIsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否已读 的本地化字符串。
        /// </summary>
        internal static string lblIsReader {
            get {
                return ResourceManager.GetString("lblIsReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 链接描述 的本地化字符串。
        /// </summary>
        internal static string lblLinkDescribe {
            get {
                return ResourceManager.GetString("lblLinkDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 链接名称 的本地化字符串。
        /// </summary>
        internal static string lblLinkName {
            get {
                return ResourceManager.GetString("lblLinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 链接方式 的本地化字符串。
        /// </summary>
        internal static string lblLinkPattern {
            get {
                return ResourceManager.GetString("lblLinkPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 链接类型 的本地化字符串。
        /// </summary>
        internal static string lblLinkType {
            get {
                return ResourceManager.GetString("lblLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 链接地址 的本地化字符串。
        /// </summary>
        internal static string lblLinkUrl {
            get {
                return ResourceManager.GetString("lblLinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 否 的本地化字符串。
        /// </summary>
        internal static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未读 的本地化字符串。
        /// </summary>
        internal static string lblNotRead {
            get {
                return ResourceManager.GetString("lblNotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 父评论 的本地化字符串。
        /// </summary>
        internal static string lblParentReplie {
            get {
                return ResourceManager.GetString("lblParentReplie", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已读 的本地化字符串。
        /// </summary>
        internal static string lblReaded {
            get {
                return ResourceManager.GetString("lblReaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发布人 的本地化字符串。
        /// </summary>
        internal static string lblReleaser {
            get {
                return ResourceManager.GetString("lblReleaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发布时间 的本地化字符串。
        /// </summary>
        internal static string lblReleaseTime {
            get {
                return ResourceManager.GetString("lblReleaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 回复数 的本地化字符串。
        /// </summary>
        internal static string lblReplies {
            get {
                return ResourceManager.GetString("lblReplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 回复人 的本地化字符串。
        /// </summary>
        internal static string lblReplyPerson {
            get {
                return ResourceManager.GetString("lblReplyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查看评论详细信息 的本地化字符串。
        /// </summary>
        internal static string lblShowComments {
            get {
                return ResourceManager.GetString("lblShowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 文字链接 的本地化字符串。
        /// </summary>
        internal static string lblTextLink {
            get {
                return ResourceManager.GetString("lblTextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是 的本地化字符串。
        /// </summary>
        internal static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图片评论 的本地化字符串。
        /// </summary>
        internal static string PictureComments {
            get {
                return ResourceManager.GetString("PictureComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 帖子评论 的本地化字符串。
        /// </summary>
        internal static string PostComments {
            get {
                return ResourceManager.GetString("PostComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 友情链接管理 的本地化字符串。
        /// </summary>
        internal static string prFriendlyLinkList {
            get {
                return ResourceManager.GetString("prFriendlyLinkList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加评论 的本地化字符串。
        /// </summary>
        internal static string ptAddComment {
            get {
                return ResourceManager.GetString("ptAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 评论管理 的本地化字符串。
        /// </summary>
        internal static string ptCommentList {
            get {
                return ResourceManager.GetString("ptCommentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 敏感词管理 的本地化字符串。
        /// </summary>
        internal static string ptFilterWord {
            get {
                return ResourceManager.GetString("ptFilterWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加友情链接 的本地化字符串。
        /// </summary>
        internal static string ptFriendlyLink {
            get {
                return ResourceManager.GetString("ptFriendlyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改友情链接 的本地化字符串。
        /// </summary>
        internal static string ptFriendlyLinkModify {
            get {
                return ResourceManager.GetString("ptFriendlyLinkModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 友情链接信息 的本地化字符串。
        /// </summary>
        internal static string ptFriendlyLinkShow {
            get {
                return ResourceManager.GetString("ptFriendlyLinkShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑评论 的本地化字符串。
        /// </summary>
        internal static string ptModifyComments {
            get {
                return ResourceManager.GetString("ptModifyComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 评论详细信息 的本地化字符串。
        /// </summary>
        internal static string ptShowComments {
            get {
                return ResourceManager.GetString("ptShowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加新商品-选择商品分类 的本地化字符串。
        /// </summary>
        internal static string ShopSelectCategory {
            get {
                return ResourceManager.GetString("ShopSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入正整数 的本地化字符串。
        /// </summary>
        internal static string TooltipInputInt {
            get {
                return ResourceManager.GetString("TooltipInputInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 视频评论 的本地化字符串。
        /// </summary>
        internal static string VideoComments {
            get {
                return ResourceManager.GetString("VideoComments", resourceCulture);
            }
        }
    }
}
