//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Site", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 年龄 的本地化字符串。
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 审核通过 的本地化字符串。
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上级类别不得与自身相同! 的本地化字符串。
        /// </summary>
        internal static string BaseDifferent {
            get {
                return ResourceManager.GetString("BaseDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加权限 &gt;&gt; 的本地化字符串。
        /// </summary>
        internal static string btnAddPermissionText {
            get {
                return ResourceManager.GetString("btnAddPermissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加 的本地化字符串。
        /// </summary>
        internal static string btnAddText {
            get {
                return ResourceManager.GetString("btnAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 重新调整 的本地化字符串。
        /// </summary>
        internal static string btnAdjustText {
            get {
                return ResourceManager.GetString("btnAdjustText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量审核 的本地化字符串。
        /// </summary>
        internal static string btnApproveListText {
            get {
                return ResourceManager.GetString("btnApproveListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 审核 的本地化字符串。
        /// </summary>
        internal static string btnApproveText {
            get {
                return ResourceManager.GetString("btnApproveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 考核 的本地化字符串。
        /// </summary>
        internal static string btnAssessmentText {
            get {
                return ResourceManager.GetString("btnAssessmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分配 的本地化字符串。
        /// </summary>
        internal static string btnAssignmentText {
            get {
                return ResourceManager.GetString("btnAssignmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string btnBackText {
            get {
                return ResourceManager.GetString("btnBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量处理 的本地化字符串。
        /// </summary>
        internal static string btnBatch {
            get {
                return ResourceManager.GetString("btnBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批设置 的本地化字符串。
        /// </summary>
        internal static string btnBatchText {
            get {
                return ResourceManager.GetString("btnBatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 计算 的本地化字符串。
        /// </summary>
        internal static string btnCalculateText {
            get {
                return ResourceManager.GetString("btnCalculateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 取消推荐 的本地化字符串。
        /// </summary>
        internal static string btnCancelRecommendListText {
            get {
                return ResourceManager.GetString("btnCancelRecommendListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string btnCancelText {
            get {
                return ResourceManager.GetString("btnCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string btnCancleText {
            get {
                return ResourceManager.GetString("btnCancleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量关闭 的本地化字符串。
        /// </summary>
        internal static string btnCloseListText {
            get {
                return ResourceManager.GetString("btnCloseListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string btnCloseText {
            get {
                return ResourceManager.GetString("btnCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 生成文件 的本地化字符串。
        /// </summary>
        internal static string btnCreateFile {
            get {
                return ResourceManager.GetString("btnCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量删除 的本地化字符串。
        /// </summary>
        internal static string btnDeleteListText {
            get {
                return ResourceManager.GetString("btnDeleteListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string btnDeleteText {
            get {
                return ResourceManager.GetString("btnDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 详细 的本地化字符串。
        /// </summary>
        internal static string btnDetailText {
            get {
                return ResourceManager.GetString("btnDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 向下 的本地化字符串。
        /// </summary>
        internal static string btnDownText {
            get {
                return ResourceManager.GetString("btnDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string btnEditText {
            get {
                return ResourceManager.GetString("btnEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您确认要移除吗？ 的本地化字符串。
        /// </summary>
        internal static string btnIfRemove {
            get {
                return ResourceManager.GetString("btnIfRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量显示 的本地化字符串。
        /// </summary>
        internal static string btnIsDisplayList {
            get {
                return ResourceManager.GetString("btnIsDisplayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量不显示 的本地化字符串。
        /// </summary>
        internal static string btnIsNotDisplayList {
            get {
                return ResourceManager.GetString("btnIsNotDisplayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string btnModifyText {
            get {
                return ResourceManager.GetString("btnModifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 移动到 的本地化字符串。
        /// </summary>
        internal static string btnMoveToText {
            get {
                return ResourceManager.GetString("btnMoveToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 下一步 的本地化字符串。
        /// </summary>
        internal static string btnNextText {
            get {
                return ResourceManager.GetString("btnNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设为无效 的本地化字符串。
        /// </summary>
        internal static string btnNotApproveList {
            get {
                return ResourceManager.GetString("btnNotApproveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量拒绝 的本地化字符串。
        /// </summary>
        internal static string btnNotApproveListText {
            get {
                return ResourceManager.GetString("btnNotApproveListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string btnOKText {
            get {
                return ResourceManager.GetString("btnOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量打开 的本地化字符串。
        /// </summary>
        internal static string btnOpenListText {
            get {
                return ResourceManager.GetString("btnOpenListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发放 的本地化字符串。
        /// </summary>
        internal static string btnPayText {
            get {
                return ResourceManager.GetString("btnPayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上一步 的本地化字符串。
        /// </summary>
        internal static string btnPreviousStep {
            get {
                return ResourceManager.GetString("btnPreviousStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string btnQueryText {
            get {
                return ResourceManager.GetString("btnQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量推荐 的本地化字符串。
        /// </summary>
        internal static string btnRecommendListText {
            get {
                return ResourceManager.GetString("btnRecommendListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 &lt;&lt; 移除权限 的本地化字符串。
        /// </summary>
        internal static string btnRemovePermissionText {
            get {
                return ResourceManager.GetString("btnRemovePermissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 从该角色移除 的本地化字符串。
        /// </summary>
        internal static string btnRemoveText {
            get {
                return ResourceManager.GetString("btnRemoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存及新增 的本地化字符串。
        /// </summary>
        internal static string btnSaveAndAdd {
            get {
                return ResourceManager.GetString("btnSaveAndAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string btnSaveText {
            get {
                return ResourceManager.GetString("btnSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string btnSearchText {
            get {
                return ResourceManager.GetString("btnSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设为无效 的本地化字符串。
        /// </summary>
        internal static string btnSetInvalidText {
            get {
                return ResourceManager.GetString("btnSetInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设为有效 的本地化字符串。
        /// </summary>
        internal static string btnSetValidText {
            get {
                return ResourceManager.GetString("btnSetValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查看 的本地化字符串。
        /// </summary>
        internal static string btnShowText {
            get {
                return ResourceManager.GetString("btnShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量结束进程 的本地化字符串。
        /// </summary>
        internal static string btnStopRouteListText {
            get {
                return ResourceManager.GetString("btnStopRouteListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string btnUpdateText {
            get {
                return ResourceManager.GetString("btnUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 向上 的本地化字符串。
        /// </summary>
        internal static string btnUpText {
            get {
                return ResourceManager.GetString("btnUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择全部 的本地化字符串。
        /// </summary>
        internal static string chkAllText {
            get {
                return ResourceManager.GetString("chkAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string Describe {
            get {
                return ResourceManager.GetString("Describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作为草稿 的本地化字符串。
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 仅好友观看 的本地化字符串。
        /// </summary>
        internal static string drpFriendsWatch {
            get {
                return ResourceManager.GetString("drpFriendsWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 仅自己可见 的本地化字符串。
        /// </summary>
        internal static string drpHimselfVisible {
            get {
                return ResourceManager.GetString("drpHimselfVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 员工 的本地化字符串。
        /// </summary>
        internal static string drpListUU {
            get {
                return ResourceManager.GetString("drpListUU", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 对所有人公开 的本地化字符串。
        /// </summary>
        internal static string drpOpenToAll {
            get {
                return ResourceManager.GetString("drpOpenToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 尾页 的本地化字符串。
        /// </summary>
        internal static string EndPage {
            get {
                return ResourceManager.GetString("EndPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加失败，请稍后再试！ 的本地化字符串。
        /// </summary>
        internal static string ErrorAddFailure {
            get {
                return ResourceManager.GetString("ErrorAddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统管理保留帐号，不能删除! 的本地化字符串。
        /// </summary>
        internal static string ErrorCannotDeleteID {
            get {
                return ResourceManager.GetString("ErrorCannotDeleteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该角色为系统保留角色，不能删除！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCannotDeleteRole {
            get {
                return ResourceManager.GetString("ErrorCannotDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该用户已被其他数据引用，不能删除！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCannotDeleteUser {
            get {
                return ResourceManager.GetString("ErrorCannotDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库执行错误。 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL {
            get {
                return ResourceManager.GetString("ErrorMessageSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 DeadLock Victim 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL1205 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL1205", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SQLServer不存在或访问被拒绝。 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL17 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL17", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 登录失败！ 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL18456 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL18456", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Unique Index/Constriant Violation. 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL2601 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL2601", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据库中已经存在相同的数据。 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL2627 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL2627", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 无效的数据库。 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL4060 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL4060", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 数据已经被其它地方引用，无法执行该操作。 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL547 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL547", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改失败，请稍后再试！ 的本地化字符串。
        /// </summary>
        internal static string ErrorModifiedFailure {
            get {
                return ResourceManager.GetString("ErrorModifiedFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网络异常，请稍后再试！ 的本地化字符串。
        /// </summary>
        internal static string ErrorNetworkAnomaly {
            get {
                return ResourceManager.GetString("ErrorNetworkAnomaly", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您尚未登录，请登录后在进行操作！ 的本地化字符串。
        /// </summary>
        internal static string ErrorNotLogin {
            get {
                return ResourceManager.GetString("ErrorNotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 不能为空 的本地化字符串。
        /// </summary>
        internal static string ErrorNotNull {
            get {
                return ResourceManager.GetString("ErrorNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 两次密码输入不符 的本地化字符串。
        /// </summary>
        internal static string ErrorPasswprd {
            get {
                return ResourceManager.GetString("ErrorPasswprd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 原密码输入错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorPasswprdError {
            get {
                return ResourceManager.GetString("ErrorPasswprdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传的图片不能超过{0}M 的本地化字符串。
        /// </summary>
        internal static string ErrorPrictureSize {
            get {
                return ResourceManager.GetString("ErrorPrictureSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统提示： 的本地化字符串。
        /// </summary>
        internal static string ErrorSystemTip {
            get {
                return ResourceManager.GetString("ErrorSystemTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上传的图片格式应为：jpg,gif,png 的本地化字符串。
        /// </summary>
        internal static string ErrorUploadPicture {
            get {
                return ResourceManager.GetString("ErrorUploadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户名不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorUserNameNotNull {
            get {
                return ResourceManager.GetString("ErrorUserNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 快速查询 的本地化字符串。
        /// </summary>
        internal static string FastQuery {
            get {
                return ResourceManager.GetString("FastQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司 的本地化字符串。
        /// </summary>
        internal static string fieldCompany {
            get {
                return ResourceManager.GetString("fieldCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密码确认 的本地化字符串。
        /// </summary>
        internal static string fieldConfirmationPassword {
            get {
                return ResourceManager.GetString("fieldConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string fieldEmail {
            get {
                return ResourceManager.GetString("fieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 管理员 的本地化字符串。
        /// </summary>
        internal static string fielDescriptionAA {
            get {
                return ResourceManager.GetString("fielDescriptionAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业用户 的本地化字符串。
        /// </summary>
        internal static string fielDescriptionEE {
            get {
                return ResourceManager.GetString("fielDescriptionEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 普通会员 的本地化字符串。
        /// </summary>
        internal static string fielDescriptionUU {
            get {
                return ResourceManager.GetString("fielDescriptionUU", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string fieldFeedback_cUserName {
            get {
                return ResourceManager.GetString("fieldFeedback_cUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string fieldFeedback_iID {
            get {
                return ResourceManager.GetString("fieldFeedback_iID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 原密码 的本地化字符串。
        /// </summary>
        internal static string fieldOldPassword {
            get {
                return ResourceManager.GetString("fieldOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string fieldPassword {
            get {
                return ResourceManager.GetString("fieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 积分明细 的本地化字符串。
        /// </summary>
        internal static string fieldPointsDetail {
            get {
                return ResourceManager.GetString("fieldPointsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置角色 的本地化字符串。
        /// </summary>
        internal static string fieldSetRoles {
            get {
                return ResourceManager.GetString("fieldSetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 性别 的本地化字符串。
        /// </summary>
        internal static string fieldSex {
            get {
                return ResourceManager.GetString("fieldSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string fieldTelphone {
            get {
                return ResourceManager.GetString("fieldTelphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 真实姓名 的本地化字符串。
        /// </summary>
        internal static string fieldTrueName {
            get {
                return ResourceManager.GetString("fieldTrueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类别名称 的本地化字符串。
        /// </summary>
        internal static string fieldUserDescription {
            get {
                return ResourceManager.GetString("fieldUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户编号 的本地化字符串。
        /// </summary>
        internal static string fieldUserID {
            get {
                return ResourceManager.GetString("fieldUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string fieldUserName {
            get {
                return ResourceManager.GetString("fieldUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户类别 的本地化字符串。
        /// </summary>
        internal static string fieldUserType {
            get {
                return ResourceManager.GetString("fieldUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 冻结 的本地化字符串。
        /// </summary>
        internal static string Freeze {
            get {
                return ResourceManager.GetString("Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量冻结 的本地化字符串。
        /// </summary>
        internal static string FreezeList {
            get {
                return ResourceManager.GetString("FreezeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导出Excel 的本地化字符串。
        /// </summary>
        internal static string GVTextExportExcel {
            get {
                return ResourceManager.GetString("GVTextExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导出Word 的本地化字符串。
        /// </summary>
        internal static string GVTextExportWord {
            get {
                return ResourceManager.GetString("GVTextExportWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第一页 的本地化字符串。
        /// </summary>
        internal static string GVTextFirst {
            get {
                return ResourceManager.GetString("GVTextFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最后一页 的本地化字符串。
        /// </summary>
        internal static string GVTextLast {
            get {
                return ResourceManager.GetString("GVTextLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string GVTextNext {
            get {
                return ResourceManager.GetString("GVTextNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 页 的本地化字符串。
        /// </summary>
        internal static string GVTextPage {
            get {
                return ResourceManager.GetString("GVTextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 上一页 的本地化字符串。
        /// </summary>
        internal static string GVTextPrevious {
            get {
                return ResourceManager.GetString("GVTextPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 记录 的本地化字符串。
        /// </summary>
        internal static string GVTextRecord {
            get {
                return ResourceManager.GetString("GVTextRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已审核 的本地化字符串。
        /// </summary>
        internal static string HaveAudited {
            get {
                return ResourceManager.GetString("HaveAudited", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 反选 的本地化字符串。
        /// </summary>
        internal static string InvertSelection {
            get {
                return ResourceManager.GetString("InvertSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加角色 的本地化字符串。
        /// </summary>
        internal static string lblAddRole {
            get {
                return ResourceManager.GetString("lblAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 审核状态 的本地化字符串。
        /// </summary>
        internal static string lblApprovalStatus {
            get {
                return ResourceManager.GetString("lblApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 类别 的本地化字符串。
        /// </summary>
        internal static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 手机 的本地化字符串。
        /// </summary>
        internal static string lblCellphone {
            get {
                return ResourceManager.GetString("lblCellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 默认图标 的本地化字符串。
        /// </summary>
        internal static string lblDefaultIcon {
            get {
                return ResourceManager.GetString("lblDefaultIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 说明 的本地化字符串。
        /// </summary>
        internal static string lblExplain {
            get {
                return ResourceManager.GetString("lblExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 否 的本地化字符串。
        /// </summary>
        internal static string lblFalse {
            get {
                return ResourceManager.GetString("lblFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 图标(16x16) 的本地化字符串。
        /// </summary>
        internal static string lblIcon {
            get {
                return ResourceManager.GetString("lblIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 简介 的本地化字符串。
        /// </summary>
        internal static string lblIntro {
            get {
                return ResourceManager.GetString("lblIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关键字 的本地化字符串。
        /// </summary>
        internal static string lblKeyword {
            get {
                return ResourceManager.GetString("lblKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新角色名 的本地化字符串。
        /// </summary>
        internal static string lblNewRoleName {
            get {
                return ResourceManager.GetString("lblNewRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string lblOperation {
            get {
                return ResourceManager.GetString("lblOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 顺序 的本地化字符串。
        /// </summary>
        internal static string lblOrder {
            get {
                return ResourceManager.GetString("lblOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 页面地址 的本地化字符串。
        /// </summary>
        internal static string lblPageUrl {
            get {
                return ResourceManager.GetString("lblPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 父类 的本地化字符串。
        /// </summary>
        internal static string lblParentClass {
            get {
                return ResourceManager.GetString("lblParentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 根目录 的本地化字符串。
        /// </summary>
        internal static string lblRootDirectory {
            get {
                return ResourceManager.GetString("lblRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string lblScan {
            get {
                return ResourceManager.GetString("lblScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string lblSerialNumber {
            get {
                return ResourceManager.GetString("lblSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string lblSet {
            get {
                return ResourceManager.GetString("lblSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 显示 的本地化字符串。
        /// </summary>
        internal static string lblShow {
            get {
                return ResourceManager.GetString("lblShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 显示序号 的本地化字符串。
        /// </summary>
        internal static string lblShowID {
            get {
                return ResourceManager.GetString("lblShowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 宋体 的本地化字符串。
        /// </summary>
        internal static string lblSimsun {
            get {
                return ResourceManager.GetString("lblSimsun", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 解决 的本地化字符串。
        /// </summary>
        internal static string lblSolve {
            get {
                return ResourceManager.GetString("lblSolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 副标题 的本地化字符串。
        /// </summary>
        internal static string lblSubtitled {
            get {
                return ResourceManager.GetString("lblSubtitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 缩略图 的本地化字符串。
        /// </summary>
        internal static string lblThumbnails {
            get {
                return ResourceManager.GetString("lblThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是 的本地化字符串。
        /// </summary>
        internal static string lblTrue {
            get {
                return ResourceManager.GetString("lblTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户IP 的本地化字符串。
        /// </summary>
        internal static string lblUserIP {
            get {
                return ResourceManager.GetString("lblUserIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string ltlAdd {
            get {
                return ResourceManager.GetString("ltlAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string ltlRefresh {
            get {
                return ResourceManager.GetString("ltlRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 参数错误 的本地化字符串。
        /// </summary>
        internal static string ParameterError {
            get {
                return ResourceManager.GetString("ParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 等待审核 的本地化字符串。
        /// </summary>
        internal static string PendingReview {
            get {
                return ResourceManager.GetString("PendingReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 --  请选择 -- 的本地化字符串。
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已处理 的本地化字符串。
        /// </summary>
        internal static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 功能行为管理 的本地化字符串。
        /// </summary>
        internal static string ptActions {
            get {
                return ResourceManager.GetString("ptActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加用户 的本地化字符串。
        /// </summary>
        internal static string ptAddUser {
            get {
                return ResourceManager.GetString("ptAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加用户类别 的本地化字符串。
        /// </summary>
        internal static string ptAddUserType {
            get {
                return ResourceManager.GetString("ptAddUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改密码 的本地化字符串。
        /// </summary>
        internal static string ptChangePassword {
            get {
                return ResourceManager.GetString("ptChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色编辑 的本地化字符串。
        /// </summary>
        internal static string ptEditRole {
            get {
                return ResourceManager.GetString("ptEditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 权限管理 的本地化字符串。
        /// </summary>
        internal static string ptPermissionAdmin {
            get {
                return ResourceManager.GetString("ptPermissionAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色管理 的本地化字符串。
        /// </summary>
        internal static string ptRoleAdmin {
            get {
                return ResourceManager.GetString("ptRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色分配 的本地化字符串。
        /// </summary>
        internal static string ptRoleAssignment {
            get {
                return ResourceManager.GetString("ptRoleAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 可分配角色设置 的本地化字符串。
        /// </summary>
        internal static string ptRoleAssignmentUserSet {
            get {
                return ResourceManager.GetString("ptRoleAssignmentUserSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户类别管理 的本地化字符串。
        /// </summary>
        internal static string ptUserAdmin {
            get {
                return ResourceManager.GetString("ptUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户信息 的本地化字符串。
        /// </summary>
        internal static string ptUserInfo {
            get {
                return ResourceManager.GetString("ptUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户角色分配管理 的本地化字符串。
        /// </summary>
        internal static string ptUserRoleAdmin {
            get {
                return ResourceManager.GetString("ptUserRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户类别管理 的本地化字符串。
        /// </summary>
        internal static string ptUserTypeAdmin {
            get {
                return ResourceManager.GetString("ptUserTypeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户更新 的本地化字符串。
        /// </summary>
        internal static string ptUserUpdate {
            get {
                return ResourceManager.GetString("ptUserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Meta描述标签 的本地化字符串。
        /// </summary>
        internal static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Meta关键字标签 的本地化字符串。
        /// </summary>
        internal static string SeoKeyWords {
            get {
                return ResourceManager.GetString("SeoKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Meta标题 的本地化字符串。
        /// </summary>
        internal static string SeoTitle {
            get {
                return ResourceManager.GetString("SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 男 的本地化字符串。
        /// </summary>
        internal static string SexMale {
            get {
                return ResourceManager.GetString("SexMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 女 的本地化字符串。
        /// </summary>
        internal static string SexWoman {
            get {
                return ResourceManager.GetString("SexWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 排序 的本地化字符串。
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string Statement {
            get {
                return ResourceManager.GetString("Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipAddSuccess {
            get {
                return ResourceManager.GetString("TooltipAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 批量更新成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipBatchUpdateOK {
            get {
                return ResourceManager.GetString("TooltipBatchUpdateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该编码已经存在，请更换其他编码。 的本地化字符串。
        /// </summary>
        internal static string TooltipCodeExist {
            get {
                return ResourceManager.GetString("TooltipCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该数据已经被其它数据使用，不能再进行修改！ 的本地化字符串。
        /// </summary>
        internal static string TooltipDataBeUsed {
            get {
                return ResourceManager.GetString("TooltipDataBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该信息已经存在！ 的本地化字符串。
        /// </summary>
        internal static string TooltipDataExist {
            get {
                return ResourceManager.GetString("TooltipDataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您确认要删除吗？ 的本地化字符串。
        /// </summary>
        internal static string TooltipDelConfirm {
            get {
                return ResourceManager.GetString("TooltipDelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除失败！ 的本地化字符串。
        /// </summary>
        internal static string TooltipDelError {
            get {
                return ResourceManager.GetString("TooltipDelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipDelOK {
            get {
                return ResourceManager.GetString("TooltipDelOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你的帐号已在别处登陆，你被强迫下线！ 的本地化字符串。
        /// </summary>
        internal static string TooltipForceLogin {
            get {
                return ResourceManager.GetString("TooltipForceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 格式不正确！ 的本地化字符串。
        /// </summary>
        internal static string TooltipFormatErr {
            get {
                return ResourceManager.GetString("TooltipFormatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 输入数据不正确！ 的本地化字符串。
        /// </summary>
        internal static string TooltipInputDataErr {
            get {
                return ResourceManager.GetString("TooltipInputDataErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你尚未登录或无权访问，请重新登录！ 的本地化字符串。
        /// </summary>
        internal static string TooltipNoAuthenticated {
            get {
                return ResourceManager.GetString("TooltipNoAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入内容！ 的本地化字符串。
        /// </summary>
        internal static string TooltipNoNull {
            get {
                return ResourceManager.GetString("TooltipNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你没有权限访问该页！请重新登录或联系管理员！ 的本地化字符串。
        /// </summary>
        internal static string TooltipNoPermission {
            get {
                return ResourceManager.GetString("TooltipNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 不是数字格式 的本地化字符串。
        /// </summary>
        internal static string TooltipNumFormatErr {
            get {
                return ResourceManager.GetString("TooltipNumFormatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作失败! 的本地化字符串。
        /// </summary>
        internal static string TooltipOperateError {
            get {
                return ResourceManager.GetString("TooltipOperateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作成功! 的本地化字符串。
        /// </summary>
        internal static string TooltipOperateOK {
            get {
                return ResourceManager.GetString("TooltipOperateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该类别下存在权限数据，不能再进行删除！请先删除关联数据！ 的本地化字符串。
        /// </summary>
        internal static string TooltipPermCateNoDelete {
            get {
                return ResourceManager.GetString("TooltipPermCateNoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确定要这样做吗？ 的本地化字符串。
        /// </summary>
        internal static string TooltipResureDoThisOperation {
            get {
                return ResourceManager.GetString("TooltipResureDoThisOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存失败！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSaveError {
            get {
                return ResourceManager.GetString("TooltipSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSaveOK {
            get {
                return ResourceManager.GetString("TooltipSaveOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你登录超时，请重新登录！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSessionExpired {
            get {
                return ResourceManager.GetString("TooltipSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 不是日期格式 的本地化字符串。
        /// </summary>
        internal static string TooltipTimeFormatErr {
            get {
                return ResourceManager.GetString("TooltipTimeFormatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统忙，请稍后再试！ 的本地化字符串。
        /// </summary>
        internal static string TooltipTryAgainLater {
            get {
                return ResourceManager.GetString("TooltipTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改失败！ 的本地化字符串。
        /// </summary>
        internal static string TooltipUpdateError {
            get {
                return ResourceManager.GetString("TooltipUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户密码更新失败 的本地化字符串。
        /// </summary>
        internal static string TooltipUpdateFailPassword {
            get {
                return ResourceManager.GetString("TooltipUpdateFailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipUpdateOK {
            get {
                return ResourceManager.GetString("TooltipUpdateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户密码更新成功 的本地化字符串。
        /// </summary>
        internal static string TooltipUpdateSuccessfulPassword {
            get {
                return ResourceManager.GetString("TooltipUpdateSuccessfulPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户已经存在！ 的本地化字符串。
        /// </summary>
        internal static string TooltipUserExist {
            get {
                return ResourceManager.GetString("TooltipUserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户类别已经存在！ 的本地化字符串。
        /// </summary>
        internal static string TooltipUserTypeExist {
            get {
                return ResourceManager.GetString("TooltipUserTypeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关键字之间以逗号分开 的本地化字符串。
        /// </summary>
        internal static string TooltripKeyword {
            get {
                return ResourceManager.GetString("TooltripKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择要设置的权限！ 的本地化字符串。
        /// </summary>
        internal static string TooltripPer {
            get {
                return ResourceManager.GetString("TooltripPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择要设置行为编号！ 的本地化字符串。
        /// </summary>
        internal static string TooltripPerNum {
            get {
                return ResourceManager.GetString("TooltripPerNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未审核 的本地化字符串。
        /// </summary>
        internal static string Unaudited {
            get {
                return ResourceManager.GetString("Unaudited", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 货币单位 的本地化字符串。
        /// </summary>
        internal static string UnitCurrency {
            get {
                return ResourceManager.GetString("UnitCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 计量单位 的本地化字符串。
        /// </summary>
        internal static string UnitMeasure {
            get {
                return ResourceManager.GetString("UnitMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 无单位 的本地化字符串。
        /// </summary>
        internal static string UnitNone {
            get {
                return ResourceManager.GetString("UnitNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未处理 的本地化字符串。
        /// </summary>
        internal static string Untreated {
            get {
                return ResourceManager.GetString("Untreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户帐号 的本地化字符串。
        /// </summary>
        internal static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
    }
}
