//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysManage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysManage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysManage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 发送 的本地化字符串。
        /// </summary>
        internal static string btnNextText {
            get {
                return ResourceManager.GetString("btnNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置功能权限 的本地化字符串。
        /// </summary>
        internal static string btnSetupPerm {
            get {
                return ResourceManager.GetString("btnSetupPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置权限 的本地化字符串。
        /// </summary>
        internal static string btnSetupText {
            get {
                return ResourceManager.GetString("btnSetupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 测试发送 的本地化字符串。
        /// </summary>
        internal static string btnTestSend {
            get {
                return ResourceManager.GetString("btnTestSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更新粉丝关注数 的本地化字符串。
        /// </summary>
        internal static string btnUpdateFansAndFellowCountText {
            get {
                return ResourceManager.GetString("btnUpdateFansAndFellowCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string btnUpdateText {
            get {
                return ResourceManager.GetString("btnUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 代理商后台 的本地化字符串。
        /// </summary>
        internal static string dropBackendAgent {
            get {
                return ResourceManager.GetString("dropBackendAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业后台 的本地化字符串。
        /// </summary>
        internal static string dropBackendEnterprise {
            get {
                return ResourceManager.GetString("dropBackendEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商家后台 的本地化字符串。
        /// </summary>
        internal static string dropBackendSupplier {
            get {
                return ResourceManager.GetString("dropBackendSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统后台 的本地化字符串。
        /// </summary>
        internal static string dropBackendSystem {
            get {
                return ResourceManager.GetString("dropBackendSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户后台 的本地化字符串。
        /// </summary>
        internal static string dropBackendUser {
            get {
                return ResourceManager.GetString("dropBackendUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 这是{0}在为您发出的测试邮件 的本地化字符串。
        /// </summary>
        internal static string EmailBodyTemplate {
            get {
                return ResourceManager.GetString("EmailBodyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 {0}发出的测试邮件 的本地化字符串。
        /// </summary>
        internal static string EmailSubjectTemplate {
            get {
                return ResourceManager.GetString("EmailSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 根目录不能选择同步创建权限，请您手动创建！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCheckedCheckBox1 {
            get {
                return ResourceManager.GetString("ErrorCheckedCheckBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 内容不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorContentNotNull {
            get {
                return ResourceManager.GetString("ErrorContentNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 所选父菜单没有设置权限因此不能选择同步创建权限，请您手动创建！ 的本地化字符串。
        /// </summary>
        internal static string ErrorCreatePermission {
            get {
                return ResourceManager.GetString("ErrorCreatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编号格式不正确 的本地化字符串。
        /// </summary>
        internal static string ErrorIDFormalError {
            get {
                return ResourceManager.GetString("ErrorIDFormalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编号不能为空 的本地化字符串。
        /// </summary>
        internal static string ErrorIDNotNull {
            get {
                return ResourceManager.GetString("ErrorIDNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入密码 的本地化字符串。
        /// </summary>
        internal static string ErrorInputPassword {
            get {
                return ResourceManager.GetString("ErrorInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 KeyName不能为空! 的本地化字符串。
        /// </summary>
        internal static string ErrorKeyNameNotNull {
            get {
                return ResourceManager.GetString("ErrorKeyNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名称不能为空 的本地化字符串。
        /// </summary>
        internal static string ErrorNameNotNull {
            get {
                return ResourceManager.GetString("ErrorNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 权限类别不能做权限使用 的本地化字符串。
        /// </summary>
        internal static string ErrorPermission {
            get {
                return ResourceManager.GetString("ErrorPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色为空，不能保存！ 的本地化字符串。
        /// </summary>
        internal static string ErrorRoleIsNull {
            get {
                return ResourceManager.GetString("ErrorRoleIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 主题不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorSubjectNotNull {
            get {
                return ResourceManager.GetString("ErrorSubjectNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 该用户信息不存在！ 的本地化字符串。
        /// </summary>
        internal static string ErrorUserInexistence {
            get {
                return ResourceManager.GetString("ErrorUserInexistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Value不能为空! 的本地化字符串。
        /// </summary>
        internal static string ErrorValueNotNull {
            get {
                return ResourceManager.GetString("ErrorValueNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 行为编号 的本地化字符串。
        /// </summary>
        internal static string fieldActionID {
            get {
                return ResourceManager.GetString("fieldActionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否生效 的本地化字符串。
        /// </summary>
        internal static string fieldActivity {
            get {
                return ResourceManager.GetString("fieldActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 描述信息 的本地化字符串。
        /// </summary>
        internal static string fieldBDescription {
            get {
                return ResourceManager.GetString("fieldBDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 浏览器 的本地化字符串。
        /// </summary>
        internal static string fieldBrowser {
            get {
                return ResourceManager.GetString("fieldBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string fieldcomment {
            get {
                return ResourceManager.GetString("fieldcomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string fieldDescription {
            get {
                return ResourceManager.GetString("fieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 员工编号 的本地化字符串。
        /// </summary>
        internal static string fieldEmployeeID {
            get {
                return ResourceManager.GetString("fieldEmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string fieldEnabled {
            get {
                return ResourceManager.GetString("fieldEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否已经解决 的本地化字符串。
        /// </summary>
        internal static string fieldFeedback_bSolved {
            get {
                return ResourceManager.GetString("fieldFeedback_bSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 反馈内容 的本地化字符串。
        /// </summary>
        internal static string fieldFeedback_cContent {
            get {
                return ResourceManager.GetString("fieldFeedback_cContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 解决结果 的本地化字符串。
        /// </summary>
        internal static string fieldFeedback_cResult {
            get {
                return ResourceManager.GetString("fieldFeedback_cResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提交时间 的本地化字符串。
        /// </summary>
        internal static string fieldFeedback_dateCreate {
            get {
                return ResourceManager.GetString("fieldFeedback_dateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误编号 的本地化字符串。
        /// </summary>
        internal static string fieldID {
            get {
                return ResourceManager.GetString("fieldID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误信息 的本地化字符串。
        /// </summary>
        internal static string fieldLoginfo {
            get {
                return ResourceManager.GetString("fieldLoginfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件地址 的本地化字符串。
        /// </summary>
        internal static string fieldMailaddress {
            get {
                return ResourceManager.GetString("fieldMailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 字段 的本地化字符串。
        /// </summary>
        internal static string fieldMultiLang_cField {
            get {
                return ResourceManager.GetString("fieldMultiLang_cField", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string fieldMultiLang_cLang {
            get {
                return ResourceManager.GetString("fieldMultiLang_cLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 字段值 的本地化字符串。
        /// </summary>
        internal static string fieldMultiLang_cValue {
            get {
                return ResourceManager.GetString("fieldMultiLang_cValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 外键值 的本地化字符串。
        /// </summary>
        internal static string fieldMultiLang_iPKValue {
            get {
                return ResourceManager.GetString("fieldMultiLang_iPKValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 启用菜单 的本地化字符串。
        /// </summary>
        internal static string fieldNodeEnable {
            get {
                return ResourceManager.GetString("fieldNodeEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单ID 的本地化字符串。
        /// </summary>
        internal static string fieldNodeID {
            get {
                return ResourceManager.GetString("fieldNodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单名称 的本地化字符串。
        /// </summary>
        internal static string fieldNodeName {
            get {
                return ResourceManager.GetString("fieldNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单类型 的本地化字符串。
        /// </summary>
        internal static string fieldNodeType {
            get {
                return ResourceManager.GetString("fieldNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string fieldOPInfo {
            get {
                return ResourceManager.GetString("fieldOPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 记录时间 的本地化字符串。
        /// </summary>
        internal static string fieldOPTime {
            get {
                return ResourceManager.GetString("fieldOPTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 顺序 的本地化字符串。
        /// </summary>
        internal static string fieldOrder {
            get {
                return ResourceManager.GetString("fieldOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作系统 的本地化字符串。
        /// </summary>
        internal static string fieldOSName {
            get {
                return ResourceManager.GetString("fieldOSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作地址 的本地化字符串。
        /// </summary>
        internal static string fieldPageUrl {
            get {
                return ResourceManager.GetString("fieldPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 父菜单 的本地化字符串。
        /// </summary>
        internal static string fieldParent {
            get {
                return ResourceManager.GetString("fieldParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 权限 的本地化字符串。
        /// </summary>
        internal static string fieldPermission {
            get {
                return ResourceManager.GetString("fieldPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 权限编号 的本地化字符串。
        /// </summary>
        internal static string fieldPermissionID {
            get {
                return ResourceManager.GetString("fieldPermissionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Session编号 的本地化字符串。
        /// </summary>
        internal static string fieldSessionID {
            get {
                return ResourceManager.GetString("fieldSessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string fieldText {
            get {
                return ResourceManager.GetString("fieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 链接 的本地化字符串。
        /// </summary>
        internal static string fieldUrl {
            get {
                return ResourceManager.GetString("fieldUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户IP 的本地化字符串。
        /// </summary>
        internal static string fieldUserIP {
            get {
                return ResourceManager.GetString("fieldUserIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加、修改、删除功能行为数据，该数据为系统初始化数据，仅开发人员可以添加。 的本地化字符串。
        /// </summary>
        internal static string lblActionExplain {
            get {
                return ResourceManager.GetString("lblActionExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 功能行为管理 的本地化字符串。
        /// </summary>
        internal static string lblActionManage {
            get {
                return ResourceManager.GetString("lblActionManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以新增网站后台菜单 的本地化字符串。
        /// </summary>
        internal static string lblAddBackendMenu {
            get {
                return ResourceManager.GetString("lblAddBackendMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加多语言数据 的本地化字符串。
        /// </summary>
        internal static string lblAddMultiLang {
            get {
                return ResourceManager.GetString("lblAddMultiLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新建导航菜单 的本地化字符串。
        /// </summary>
        internal static string lblAddNavigationMenu {
            get {
                return ResourceManager.GetString("lblAddNavigationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以进行新增导航菜单操作 的本地化字符串。
        /// </summary>
        internal static string lblAddNewMenu {
            get {
                return ResourceManager.GetString("lblAddNewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以进行新增用户操作 的本地化字符串。
        /// </summary>
        internal static string lblAddNewUserOperate {
            get {
                return ResourceManager.GetString("lblAddNewUserOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加权限数据： 的本地化字符串。
        /// </summary>
        internal static string lblAddPermissions {
            get {
                return ResourceManager.GetString("lblAddPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加权限类别： 的本地化字符串。
        /// </summary>
        internal static string lblAddPermissionsClass {
            get {
                return ResourceManager.GetString("lblAddPermissionsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增用户 的本地化字符串。
        /// </summary>
        internal static string lblAddUser {
            get {
                return ResourceManager.GetString("lblAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以进行增加用户类别操作 的本地化字符串。
        /// </summary>
        internal static string lblAddUserTypeOperate {
            get {
                return ResourceManager.GetString("lblAddUserTypeOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你可以自定义基本设置参数 的本地化字符串。
        /// </summary>
        internal static string lblBasicConfig {
            get {
                return ResourceManager.GetString("lblBasicConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 营业时间 的本地化字符串。
        /// </summary>
        internal static string lblBusinessHours {
            get {
                return ResourceManager.GetString("lblBusinessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以清除缓存 的本地化字符串。
        /// </summary>
        internal static string lblCanClearCache {
            get {
                return ResourceManager.GetString("lblCanClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对密码进行修改 的本地化字符串。
        /// </summary>
        internal static string lblChangePassword {
            get {
                return ResourceManager.GetString("lblChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择权限类别： 的本地化字符串。
        /// </summary>
        internal static string lblChoisePermissionsClass {
            get {
                return ResourceManager.GetString("lblChoisePermissionsClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 清除成功！ 的本地化字符串。
        /// </summary>
        internal static string lblClearSucceed {
            get {
                return ResourceManager.GetString("lblClearSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司地址 的本地化字符串。
        /// </summary>
        internal static string lblCompanyAddress {
            get {
                return ResourceManager.GetString("lblCompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 传真 的本地化字符串。
        /// </summary>
        internal static string lblCompanyFax {
            get {
                return ResourceManager.GetString("lblCompanyFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你可以自定义公司基本信息 的本地化字符串。
        /// </summary>
        internal static string lblCompanyInfoConfig {
            get {
                return ResourceManager.GetString("lblCompanyInfoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string lblCompanyMail {
            get {
                return ResourceManager.GetString("lblCompanyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司名称 的本地化字符串。
        /// </summary>
        internal static string lblCompanyName {
            get {
                return ResourceManager.GetString("lblCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string lblCompanyTelephone {
            get {
                return ResourceManager.GetString("lblCompanyTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统关键参数配置。该数据为系统初始化数据，仅开发人员可以添加和编辑。 的本地化字符串。
        /// </summary>
        internal static string lblConfigSystem {
            get {
                return ResourceManager.GetString("lblConfigSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 配置SMTP邮件服务器地址，用于实现给用户发送邮件功能。 的本地化字符串。
        /// </summary>
        internal static string lblConfiguringMailbox {
            get {
                return ResourceManager.GetString("lblConfiguringMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对网站邮件进行配置 的本地化字符串。
        /// </summary>
        internal static string lblConfiguringWebsiteEmails {
            get {
                return ResourceManager.GetString("lblConfiguringWebsiteEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以查看整个网站的错误日志 的本地化字符串。
        /// </summary>
        internal static string lblConsultErrorlog {
            get {
                return ResourceManager.GetString("lblConsultErrorlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以查看整个网站的操作日志 的本地化字符串。
        /// </summary>
        internal static string lblConsultOperatelog {
            get {
                return ResourceManager.GetString("lblConsultOperatelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对客户反馈的信息进行管理 的本地化字符串。
        /// </summary>
        internal static string lblCustomerFeedbackManage {
            get {
                return ResourceManager.GetString("lblCustomerFeedbackManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 定制收藏 的本地化字符串。
        /// </summary>
        internal static string lblCustomFavoritesMenu {
            get {
                return ResourceManager.GetString("lblCustomFavoritesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以自定义后台快捷菜单 的本地化字符串。
        /// </summary>
        internal static string lblCustomShortcutMenu {
            get {
                return ResourceManager.GetString("lblCustomShortcutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 日期格式 的本地化字符串。
        /// </summary>
        internal static string lblDateFormat {
            get {
                return ResourceManager.GetString("lblDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除日期之前 的本地化字符串。
        /// </summary>
        internal static string lblDeleteBeforeOneDay {
            get {
                return ResourceManager.GetString("lblDeleteBeforeOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 配送区域 的本地化字符串。
        /// </summary>
        internal static string lblDeliveryArea {
            get {
                return ResourceManager.GetString("lblDeliveryArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑用户信息 的本地化字符串。
        /// </summary>
        internal static string lblEditUserinfo {
            get {
                return ResourceManager.GetString("lblEditUserinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已禁用 的本地化字符串。
        /// </summary>
        internal static string lblEnableFalse {
            get {
                return ResourceManager.GetString("lblEnableFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 正在使用 的本地化字符串。
        /// </summary>
        internal static string lblEnableTrue {
            get {
                return ResourceManager.GetString("lblEnableTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 企业名称： 的本地化字符串。
        /// </summary>
        internal static string lblEnterpriseName {
            get {
                return ResourceManager.GetString("lblEnterpriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 粉丝数 的本地化字符串。
        /// </summary>
        internal static string lblFansCount {
            get {
                return ResourceManager.GetString("lblFansCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户反馈管理 的本地化字符串。
        /// </summary>
        internal static string lblFeedbackList {
            get {
                return ResourceManager.GetString("lblFeedbackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户反馈信息查看 的本地化字符串。
        /// </summary>
        internal static string lblFeedbackListShow {
            get {
                return ResourceManager.GetString("lblFeedbackListShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关注数 的本地化字符串。
        /// </summary>
        internal static string lblFellowCount {
            get {
                return ResourceManager.GetString("lblFellowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 前台语言 的本地化字符串。
        /// </summary>
        internal static string lblForegroundLanguage {
            get {
                return ResourceManager.GetString("lblForegroundLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 冻结账号 的本地化字符串。
        /// </summary>
        internal static string lblFrozenAccount {
            get {
                return ResourceManager.GetString("lblFrozenAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件群发 的本地化字符串。
        /// </summary>
        internal static string lblGroupMail {
            get {
                return ResourceManager.GetString("lblGroupMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你可以自定义基本信息 的本地化字符串。
        /// </summary>
        internal static string lblInfoConfig {
            get {
                return ResourceManager.GetString("lblInfoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 作为部门内部公有部分出现 的本地化字符串。
        /// </summary>
        internal static string lblKeshiPublicText {
            get {
                return ResourceManager.GetString("lblKeshiPublicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以查看用户信息 的本地化字符串。
        /// </summary>
        internal static string lblLookUpUserinfo {
            get {
                return ResourceManager.GetString("lblLookUpUserinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单项目 的本地化字符串。
        /// </summary>
        internal static string lblMenuList {
            get {
                return ResourceManager.GetString("lblMenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以进行菜单信息 的本地化字符串。
        /// </summary>
        internal static string lblMenuShow {
            get {
                return ResourceManager.GetString("lblMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 消息内容 的本地化字符串。
        /// </summary>
        internal static string lblMessageContent {
            get {
                return ResourceManager.GetString("lblMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 消息主题 的本地化字符串。
        /// </summary>
        internal static string lblMessageSubject {
            get {
                return ResourceManager.GetString("lblMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑用户信息 的本地化字符串。
        /// </summary>
        internal static string lblModifUser {
            get {
                return ResourceManager.GetString("lblModifUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以进行编辑用户信息操作 的本地化字符串。
        /// </summary>
        internal static string lblModifUserOperate {
            get {
                return ResourceManager.GetString("lblModifUserOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑网站后台菜单 的本地化字符串。
        /// </summary>
        internal static string lblModifyBackendMenu {
            get {
                return ResourceManager.GetString("lblModifyBackendMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未归属任何部门 的本地化字符串。
        /// </summary>
        internal static string lblModuledeptText {
            get {
                return ResourceManager.GetString("lblModuledeptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未归属任何模块 的本地化字符串。
        /// </summary>
        internal static string lblModuleText {
            get {
                return ResourceManager.GetString("lblModuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以创建字段的多语言数据，实现数据的多语言管理。 的本地化字符串。
        /// </summary>
        internal static string lblMultiLanguage {
            get {
                return ResourceManager.GetString("lblMultiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 (留空将不改变原密码) 的本地化字符串。
        /// </summary>
        internal static string lblNoChangePasswpord {
            get {
                return ResourceManager.GetString("lblNoChangePasswpord", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以查看当前时间在线活动的用户 的本地化字符串。
        /// </summary>
        internal static string lblOnlineUser {
            get {
                return ResourceManager.GetString("lblOnlineUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 页面标题 的本地化字符串。
        /// </summary>
        internal static string lblPageTitle {
            get {
                return ResourceManager.GetString("lblPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 按父级菜单位置 的本地化字符串。
        /// </summary>
        internal static string lblParentMenu {
            get {
                return ResourceManager.GetString("lblParentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 没有权限限制 的本地化字符串。
        /// </summary>
        internal static string lblPermissionText {
            get {
                return ResourceManager.GetString("lblPermissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 POP服务器 的本地化字符串。
        /// </summary>
        internal static string lblPOPServer {
            get {
                return ResourceManager.GetString("lblPOPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 POP服务器端口 的本地化字符串。
        /// </summary>
        internal static string lblPOPServerPort {
            get {
                return ResourceManager.GetString("lblPOPServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你可以自定义会员注册声明 的本地化字符串。
        /// </summary>
        internal static string lblRegistStatement {
            get {
                return ResourceManager.GetString("lblRegistStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以增加权限类别和增加权限管理操作 的本地化字符串。
        /// </summary>
        internal static string lblRightsManagement {
            get {
                return ResourceManager.GetString("lblRightsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以进行角色分配操作 的本地化字符串。
        /// </summary>
        internal static string lblRoleAssignmentOperate {
            get {
                return ResourceManager.GetString("lblRoleAssignmentOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以添加角色，或点击角色名称进行角色的权限设置。 的本地化字符串。
        /// </summary>
        internal static string lblRoleManageOperate {
            get {
                return ResourceManager.GetString("lblRoleManageOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以更新角色名称和选择配置角色的权限信息。 的本地化字符串。
        /// </summary>
        internal static string lblRoleRedactOperate {
            get {
                return ResourceManager.GetString("lblRoleRedactOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信息检索，您可以有选择的选取相应条件进行检索，不填写表示不加以限制。 的本地化字符串。
        /// </summary>
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询选项 的本地化字符串。
        /// </summary>
        internal static string lblSearchCriteria {
            get {
                return ResourceManager.GetString("lblSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以自己定义邮件内容，并将邮件发送给符合查询条件的所有会员或代理商 的本地化字符串。
        /// </summary>
        internal static string lblSendMail {
            get {
                return ResourceManager.GetString("lblSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送给单个用户 的本地化字符串。
        /// </summary>
        internal static string lblSendMailToUser {
            get {
                return ResourceManager.GetString("lblSendMailToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 群发给多个用户 的本地化字符串。
        /// </summary>
        internal static string lblSendMailToUsers {
            get {
                return ResourceManager.GetString("lblSendMailToUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送对象 的本地化字符串。
        /// </summary>
        internal static string lblSendTo {
            get {
                return ResourceManager.GetString("lblSendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 起送价格 的本地化字符串。
        /// </summary>
        internal static string lblSentPrices {
            get {
                return ResourceManager.GetString("lblSentPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 服务半径 的本地化字符串。
        /// </summary>
        internal static string lblServiceRadius {
            get {
                return ResourceManager.GetString("lblServiceRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮箱地址 的本地化字符串。
        /// </summary>
        internal static string lblSMTPMail {
            get {
                return ResourceManager.GetString("lblSMTPMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户密码 的本地化字符串。
        /// </summary>
        internal static string lblSMTPPassword {
            get {
                return ResourceManager.GetString("lblSMTPPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SMTP服务器 的本地化字符串。
        /// </summary>
        internal static string lblSMTPServer {
            get {
                return ResourceManager.GetString("lblSMTPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SMTP服务器端口 的本地化字符串。
        /// </summary>
        internal static string lblSMTPServerPort {
            get {
                return ResourceManager.GetString("lblSMTPServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string lblSMTPUsername {
            get {
                return ResourceManager.GetString("lblSMTPUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 安全连接(SSL) 的本地化字符串。
        /// </summary>
        internal static string lblSSl {
            get {
                return ResourceManager.GetString("lblSSl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 状态： 的本地化字符串。
        /// </summary>
        internal static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 风格一 的本地化字符串。
        /// </summary>
        internal static string lblStyleOne {
            get {
                return ResourceManager.GetString("lblStyleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 风格二 的本地化字符串。
        /// </summary>
        internal static string lblStyleTwo {
            get {
                return ResourceManager.GetString("lblStyleTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string lblTelephone {
            get {
                return ResourceManager.GetString("lblTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 时间格式 的本地化字符串。
        /// </summary>
        internal static string lblTimeFormat {
            get {
                return ResourceManager.GetString("lblTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 时区信息 的本地化字符串。
        /// </summary>
        internal static string lblTimeZoneInformation {
            get {
                return ResourceManager.GetString("lblTimeZoneInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以对网站的菜单进行管理 的本地化字符串。
        /// </summary>
        internal static string lbltreeList {
            get {
                return ResourceManager.GetString("lbltreeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以进行用户更新操作 的本地化字符串。
        /// </summary>
        internal static string lblUpdateUserOperate {
            get {
                return ResourceManager.GetString("lblUpdateUserOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以进行新增、编辑用户信息操作 的本地化字符串。
        /// </summary>
        internal static string lblUserinfoOp {
            get {
                return ResourceManager.GetString("lblUserinfoOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以进行新增、编辑、删除用户信息操作 的本地化字符串。
        /// </summary>
        internal static string lblUserinfoOperate {
            get {
                return ResourceManager.GetString("lblUserinfoOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 您可以编辑用户类别数据。该数据为系统初始化数据，仅开发人员可以添加。 的本地化字符串。
        /// </summary>
        internal static string lblUserTypeManageOperate {
            get {
                return ResourceManager.GetString("lblUserTypeManageOperate", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网站备案号 的本地化字符串。
        /// </summary>
        internal static string lblWebsiteApprove {
            get {
                return ResourceManager.GetString("lblWebsiteApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你可以自定义网站设置参数 的本地化字符串。
        /// </summary>
        internal static string lblWebSiteConfig {
            get {
                return ResourceManager.GetString("lblWebSiteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网站版权信息 的本地化字符串。
        /// </summary>
        internal static string lblWebSiteCopyright {
            get {
                return ResourceManager.GetString("lblWebSiteCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 站点描述 的本地化字符串。
        /// </summary>
        internal static string lblWebSiteDescribe {
            get {
                return ResourceManager.GetString("lblWebSiteDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网站域名 的本地化字符串。
        /// </summary>
        internal static string lblWebSiteDomain {
            get {
                return ResourceManager.GetString("lblWebSiteDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 站点关键字 的本地化字符串。
        /// </summary>
        internal static string lblWebSiteKeywords {
            get {
                return ResourceManager.GetString("lblWebSiteKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网站 Logo 的本地化字符串。
        /// </summary>
        internal static string lblWebSiteLogo {
            get {
                return ResourceManager.GetString("lblWebSiteLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网站名称 的本地化字符串。
        /// </summary>
        internal static string lblWebSiteName {
            get {
                return ResourceManager.GetString("lblWebSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 为了提高前台网页的打开速度，建议将图片文件的大小限制在200KB以内。 的本地化字符串。
        /// </summary>
        internal static string lblWerSitePrompt {
            get {
                return ResourceManager.GetString("lblWerSitePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string ListItemAll {
            get {
                return ResourceManager.GetString("ListItemAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部菜单 的本地化字符串。
        /// </summary>
        internal static string listTargetOne {
            get {
                return ResourceManager.GetString("listTargetOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 根目录 的本地化字符串。
        /// </summary>
        internal static string listTargetTwo {
            get {
                return ResourceManager.GetString("listTargetTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 （关联用户） 的本地化字符串。
        /// </summary>
        internal static string lstDefaultUser {
            get {
                return ResourceManager.GetString("lstDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单顺序调整 的本地化字符串。
        /// </summary>
        internal static string ptAdjustmentMenuOrder {
            get {
                return ResourceManager.GetString("ptAdjustmentMenuOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 基本设置 的本地化字符串。
        /// </summary>
        internal static string ptBasicConfig {
            get {
                return ResourceManager.GetString("ptBasicConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 清除缓存 的本地化字符串。
        /// </summary>
        internal static string ptClearCache {
            get {
                return ResourceManager.GetString("ptClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司基本信息 的本地化字符串。
        /// </summary>
        internal static string ptCompanyInfoConfig {
            get {
                return ResourceManager.GetString("ptCompanyInfoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统配置 的本地化字符串。
        /// </summary>
        internal static string ptConfigSystem {
            get {
                return ResourceManager.GetString("ptConfigSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加配置 的本地化字符串。
        /// </summary>
        internal static string ptConfigurationAdd {
            get {
                return ResourceManager.GetString("ptConfigurationAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误日志 的本地化字符串。
        /// </summary>
        internal static string ptErrorlog {
            get {
                return ResourceManager.GetString("ptErrorlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户反馈 的本地化字符串。
        /// </summary>
        internal static string ptFeedbackList {
            get {
                return ResourceManager.GetString("ptFeedbackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 客户反馈信息 的本地化字符串。
        /// </summary>
        internal static string ptFeedbackListShow {
            get {
                return ResourceManager.GetString("ptFeedbackListShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件群发页 的本地化字符串。
        /// </summary>
        internal static string ptGroupEmail {
            get {
                return ResourceManager.GetString("ptGroupEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 基本信息 的本地化字符串。
        /// </summary>
        internal static string ptInfoConfig {
            get {
                return ResourceManager.GetString("ptInfoConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件发送设置 的本地化字符串。
        /// </summary>
        internal static string ptMailSendSettings {
            get {
                return ResourceManager.GetString("ptMailSendSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新建菜单 的本地化字符串。
        /// </summary>
        internal static string ptMenuAdd {
            get {
                return ResourceManager.GetString("ptMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单管理 的本地化字符串。
        /// </summary>
        internal static string ptMenuManage {
            get {
                return ResourceManager.GetString("ptMenuManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单编辑 的本地化字符串。
        /// </summary>
        internal static string ptMenuModify {
            get {
                return ResourceManager.GetString("ptMenuModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单信息 的本地化字符串。
        /// </summary>
        internal static string ptMenuShow {
            get {
                return ResourceManager.GetString("ptMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 多语言管理 的本地化字符串。
        /// </summary>
        internal static string ptMultiLanguage {
            get {
                return ResourceManager.GetString("ptMultiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 在线用户 的本地化字符串。
        /// </summary>
        internal static string ptOnlineUser {
            get {
                return ResourceManager.GetString("ptOnlineUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件配置 的本地化字符串。
        /// </summary>
        internal static string ptptMailSettings {
            get {
                return ResourceManager.GetString("ptptMailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 会员注册声明 的本地化字符串。
        /// </summary>
        internal static string ptRegistStatement {
            get {
                return ResourceManager.GetString("ptRegistStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信息检索 的本地化字符串。
        /// </summary>
        internal static string ptSearch {
            get {
                return ResourceManager.GetString("ptSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 设置用户密码 的本地化字符串。
        /// </summary>
        internal static string ptSetPass {
            get {
                return ResourceManager.GetString("ptSetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单定制 的本地化字符串。
        /// </summary>
        internal static string ptTreeFavorite {
            get {
                return ResourceManager.GetString("ptTreeFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户日志 的本地化字符串。
        /// </summary>
        internal static string ptUserLog {
            get {
                return ResourceManager.GetString("ptUserLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 网站设置 的本地化字符串。
        /// </summary>
        internal static string ptWebSiteConfig {
            get {
                return ResourceManager.GetString("ptWebSiteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 连续添加 的本地化字符串。
        /// </summary>
        internal static string TooltipAddContinue {
            get {
                return ResourceManager.GetString("TooltipAddContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择该选项,将创建同名权限,并自动绑定.注意:如果父类为根目录则不能使用该设置 的本地化字符串。
        /// </summary>
        internal static string tooltipCheckedCheckBox1 {
            get {
                return ResourceManager.GetString("tooltipCheckedCheckBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建同名的权限 的本地化字符串。
        /// </summary>
        internal static string TooltipCreatSamePerm {
            get {
                return ResourceManager.GetString("TooltipCreatSamePerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单编号 的本地化字符串。
        /// </summary>
        internal static string TooltipMenuID {
            get {
                return ResourceManager.GetString("TooltipMenuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 测试邮件发送成功，请注意查收！ 的本地化字符串。
        /// </summary>
        internal static string TooltipNoteToCheck {
            get {
                return ResourceManager.GetString("TooltipNoteToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送检索邮件时是否使用SSL 的本地化字符串。
        /// </summary>
        internal static string TooltipPOPSSl {
            get {
                return ResourceManager.GetString("TooltipPOPSSl", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 测试邮件发送失败，请稍后再试！ 的本地化字符串。
        /// </summary>
        internal static string TooltipRetryAfter {
            get {
                return ResourceManager.GetString("TooltipRetryAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请为用户选择角色 的本地化字符串。
        /// </summary>
        internal static string TooltipRoleAssignForuser {
            get {
                return ResourceManager.GetString("TooltipRoleAssignForuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件发送失败！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSentFailed {
            get {
                return ResourceManager.GetString("TooltipSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 邮件发送成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSentSuccessfully {
            get {
                return ResourceManager.GetString("TooltipSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 发送邮件时是否使用SSL 的本地化字符串。
        /// </summary>
        internal static string TooltipSMTPSSL {
            get {
                return ResourceManager.GetString("TooltipSMTPSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单说明的关键字 的本地化字符串。
        /// </summary>
        internal static string TooltiptxtDescription {
            get {
                return ResourceManager.GetString("TooltiptxtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 菜单名称关键字 的本地化字符串。
        /// </summary>
        internal static string TooltipTxtName {
            get {
                return ResourceManager.GetString("TooltipTxtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更新用户信息时发生错误，更新失败！ 的本地化字符串。
        /// </summary>
        internal static string TooltipUpdateFail {
            get {
                return ResourceManager.GetString("TooltipUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户信息更新成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipUpdateSucceed {
            get {
                return ResourceManager.GetString("TooltipUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请为用户分配可用角色 的本地化字符串。
        /// </summary>
        internal static string TooltipUserRoleAssignForuser {
            get {
                return ResourceManager.GetString("TooltipUserRoleAssignForuser", resourceCulture);
            }
        }
    }
}
